/**
 * Secondary category template: an inspired-by channel-look upholstered storage
 * bench (the kind boutique retailers sell for $1,000+). Used by the mock
 * pipeline for upholstery / sewing category projects, then adapted to the
 * user's constraints by generators.ts.
 *
 * A complete, valid BuildPlan: every section populated with real specs
 * (HD36 foam, T50 staple sizes, real fabric yardage math). Budget lines are
 * arithmetic-consistent with the totals.
 */
import type { BuildPlan } from "../../../shared/types";

const T = "2026-07-01T09:00:00.000Z";

export const upholsteredBenchTemplate: BuildPlan = {
  id: "tpl_upholstered_bench",
  projectId: "tpl_project",
  title: "Upholstered Storage Bench - Balanced Build",
  snapshot: {
    inspiredBy: "Designer boucle upholstered storage bench (user-provided reference)",
    projectType: "Upholstered item",
    selectedBuildPath: "balanced",
    difficulty: "Confident beginner",
    estimatedCostLow: 297,
    estimatedCostHigh: 470,
    estimatedTime: "1-2 weekends (12-16 hours hands-on)",
    visualMatchScore: 80,
    durabilityScore: 82,
    safetyRiskLabel: "Low-medium (basic power tools; lid pinch point addressed)",
    bestFor: "A first upholstery project with basic woodworking - staple gun skills, no sewing machine required",
    requiredWorkspace: "A garage bay or large room with a 4 x 8 ft cutting area and a clean fabric zone",
    mainMaterials: [
      "3/4 in. birch plywood box (one sheet)",
      "2 in. HD36 high-density upholstery foam",
      "Boucle-look performance fabric, 54 in. wide",
      "Dacron upholstery batting",
    ],
    keyTools: ["Staple gun (T50)", "Drill/driver", "Circular saw or store cuts", "Pocket hole jig", "Scissors + serrated knife for foam"],
  },
  worthItScore: {
    score: 85,
    verdict: "excellent",
    savingsPotential: 88,
    difficultyFit: 84,
    toolAccessibility: 90,
    materialAvailability: 82,
    visualMatchPotential: 80,
    safetyRisk: 88,
    timeCommitment: 82,
    explanation:
      "Upholstered benches are one of the best-value dupes in furniture: the retail price is mostly labor and brand markup, while the materials - a plywood box, foam, batting, and fabric - run a quarter of the tag. Staple-gun upholstery is genuinely beginner-friendly because every staple is hidden and the batting forgives small errors. The single make-or-break choice is the fabric: a proper upholstery-weight boucle-look bolt reads high-end; a thin fashion fabric reads like a costume. Foam is the second-biggest line - do not cheap out to 1 in. or low-density foam or the seat bottoms out in a month.",
    recommendation:
      "Build it. Get the box store-cut if you do not own a saw, spend the savings on the correct HD36 foam and an upholstery-weight fabric, and follow the corner-fold mini-lesson on scrap batting first. This is a very achievable weekend-and-a-half project.",
  },
  savingsStory: {
    referencePrice: 1199,
    referenceLabel: "Estimated retail (~$1,199 - typical for boutique upholstered storage benches; verify on the product page)",
    estimatedDiyCostLow: 297,
    estimatedDiyCostHigh: 470,
    estimatedSavings: 816,
    savingsPercentage: 68,
    toolCostsIncluded: false,
    laborTimeTradeoff:
      "Roughly 12-16 hands-on hours for $700-$900 in savings - about $50-$70 per hour of your time, and you get to pick a better fabric than the retailer offers.",
    explanation:
      "The DIY range covers one sheet of plywood, correct-spec HD36 foam, upholstery-weight fabric at $18-35/yd, batting, hinge hardware with a soft-close lid stay, and legs. The low end assumes sale-rack fabric and skipping optional extras; the high end pads fabric to premium performance-weave pricing plus a mis-cut buffer. Tools are excluded; a $25-40 staple gun is the only one most households are missing.",
  },
  referenceAnalysis:
    "The reference is a rectangular storage bench whose identity comes from three things: a clean fully-upholstered box with crisp vertical corners, a thick padded lid with softly rounded edges, and a nubby light-toned boucle-style fabric that photographs like a cloud. Construction under the fabric is almost certainly a plywood or engineered-wood box - exactly what we build. The upholstery is plain-wrapped on the body with a channel or waterfall look on some retail versions; our balanced path uses a clean plain wrap that an first-timer can execute crisply, with a channel-look upgrade described in the alternatives.",
  referenceAnalysisDetails: {
    shapeForm: "Rectangular box bench, fully upholstered, thick padded hinged lid, small tapered or recessed legs; crisp edges softened by batting.",
    approxDimensions: "Estimated 48 in. W x 18 in. D x 19 in. H seat height - standard end-of-bed / entryway bench sizing.",
    materials: "Engineered wood box, high-density foam seat pad, polyester boucle-type fabric, dust-cover bottom, metal or wood legs.",
    finishColor: "Light cream/ivory nubby boucle-look weave; legs in natural wood or matte black.",
    constructionStyle: "Factory: stapled upholstery over a frame/box, sewn lid cover with piped or waterfall edges, hinged storage compartment.",
    decorativeDetails: "The fabric texture IS the design - plus the thick soft-edged lid and a tight shadow reveal at the floor line.",
    visible: [
      "Nubby boucle-style fabric texture on every face",
      "Thick (2 in.+) padded lid with rounded edge profile",
      "Clean vertical corners with no visible seams on the front face",
      "Small legs creating a floor shadow line",
    ],
    uncertain: [
      "Exact dimensions (estimated from standard bench sizing unless the product page lists them)",
      "Hinge hardware and whether the retail lid has a soft-close stay",
      "Foam density used by the factory (we spec HD36 regardless - it outlasts most factory foam)",
      "Fabric fiber content and rub-count rating",
    ],
  },
  confidenceBreakdown: {
    overall: 78,
    referenceImage: 75,
    materials: 85,
    dimensions: 65,
    finish: 80,
    construction: 85,
    cost: 78,
    safety: 90,
    visualMatch: 80,
    uncertaintyNotes: [
      "Dimensions are standard-sizing estimates unless the product page listed them - verify the width against your space before cutting.",
      "Fabric is the visual-match wildcard: the same build in a great boucle-look bolt scores 85+, in a thin fashion fabric it scores 55.",
      "Foam pricing swings widely between craft-store list price and their perpetual 40-50 percent coupons - the budget range covers both.",
    ],
    howToImproveConfidence: [
      "Paste the product page dimensions section if available.",
      "Order 2-3 fabric swatches before committing yardage - texture and tone in hand beat any screen photo.",
      "Sit-test any bench of similar height at a store: 18-19 in. suits most adults, but confirm for your household.",
    ],
  },
  feasibilityQuestions: [
    {
      id: "q_storage",
      question: "Do you want the hinged storage compartment, or a simpler fixed-top bench?",
      whyItMatters:
        "The hinge, lid stay, and lid-fit tolerances are most of the fussy work. A fixed top cuts 3-4 hours and about $30, but you lose roughly 3 cubic feet of hidden storage.",
      answerType: "single_choice",
      options: ["Hinged storage lid", "Fixed top, no storage"],
      requiredForSafety: false,
      assumptionIfSkipped: "We assume the hinged storage lid - it is the version in most reference photos.",
    },
    {
      id: "q_kids_lid",
      question: "Will small children use or climb on this bench?",
      whyItMatters:
        "A falling storage-bench lid is a real finger-crush hazard for small hands. With kids in the house we require a soft-close lid support (about $12-18) and spec ventilation gaps so the box is never airtight.",
      answerType: "boolean",
      requiredForSafety: true,
      assumptionIfSkipped:
        "We assume yes and include the soft-close lid stay as REQUIRED hardware plus a no-airtight-seal note. Skip it only for a childfree household, and honestly not even then.",
    },
    {
      id: "q_fabric",
      question: "What fabric direction do you want: light boucle-look (like most references), a performance weave (kids/pets), or velvet?",
      whyItMatters:
        "It sets the shopping list and the care instructions. Light boucle photographs best but shows soil; performance weaves survive kids and pets; velvet reads formal and shows sit-marks.",
      answerType: "single_choice",
      options: ["Light boucle-look", "Performance weave (stain-resistant)", "Velvet", "Not sure - show options"],
      requiredForSafety: false,
      assumptionIfSkipped: "We assume a boucle-look upholstery-weight polyester (15,000+ double rubs) in cream - the reference look.",
    },
    {
      id: "q_size",
      question: "Where will the bench live, and does 48 in. wide x 18 in. deep fit with walking room?",
      whyItMatters:
        "End-of-bed wants the bench 2-4 in. narrower than the bed frame; entryways want 36 in. of walkway in front. Shrinking to 36 or 42 in. wide changes the cut sheet but nothing else.",
      answerType: "text",
      requiredForSafety: false,
      assumptionIfSkipped: "We assume 48 x 18 x 19 in. - the standard queen-bed / entryway size.",
    },
  ],
  assumptions: [
    "Reference retail price assumed around $1,199 - typical for this category; not verified against a live page.",
    "Overall size assumed 48 in. W x 18 in. D x 19 in. H (12 in. box + 2-3/4 in. padded lid + 4-1/2 in. legs).",
    "HD36 (1.8 lb/cu ft density, 36 lb compression) foam specified for the seat - the standard for daily-sit upholstery. Cheaper 'craft foam' is a different product and will not hold up.",
    "Fabric math assumes 54 in. wide upholstery yardage: 2.5 yd covers the lid, box wrap, and pattern-matching margin at this size.",
    "One 4x8 sheet of 3/4 in. plywood yields the entire box with ~25 percent left over.",
    "Prices are mid-2026 big-box plus fabric/craft store averages; fabric is the volatile line (sales swing it 40 percent).",
  ],
  buildPaths: [
    {
      id: "path_mvd",
      name: "minimum_viable_dupe",
      label: "Minimum Viable Dupe",
      estimatedCostLow: 140,
      estimatedCostHigh: 220,
      estimatedTime: "1 weekend (6-8 hours)",
      difficulty: "Beginner",
      visualMatchScore: 55,
      durabilityScore: 65,
      requiredTools: ["Staple gun", "Drill/driver", "Store cuts for all panels"],
      pros: ["Cheapest path to the silhouette", "No hinge fitting - fixed top", "All cuts made at the store"],
      cons: ["No storage", "1 in. economy foam feels firm-board-like within a year of daily sitting", "Budget fabric shows its price up close"],
      bestFor: "A looks-first hallway bench that gets sat on for 30 seconds at a time",
      compromises: ["Fixed top", "Thinner foam", "Clearance-rack fabric", "Screw-on dome feet instead of legs"],
    },
    {
      id: "path_budget",
      name: "budget",
      label: "Budget Build",
      estimatedCostLow: 200,
      estimatedCostHigh: 310,
      estimatedTime: "1-2 weekends (10-13 hours)",
      difficulty: "Beginner",
      visualMatchScore: 68,
      durabilityScore: 75,
      requiredTools: ["Staple gun", "Drill/driver", "Pocket hole jig (or butt joints + screws)", "Store cuts"],
      pros: ["Keeps the storage lid and correct 2 in. foam on the seat", "Fabric from the mid-price bolt wall with a coupon", "Real legs, basic hinge"],
      cons: ["1 in. foam on the box sides instead of batting-only wrap - slightly boxier look", "Standard hinge without soft-close (add the stay if kids are around)"],
      bestFor: "Full function at the lowest sensible spend",
      compromises: ["Mid-grade fabric", "Simpler edge profile on the lid"],
    },
    {
      id: "path_balanced",
      name: "balanced",
      label: "Balanced Build",
      estimatedCostLow: 297,
      estimatedCostHigh: 470,
      estimatedTime: "1-2 weekends (12-16 hours)",
      difficulty: "Confident beginner",
      visualMatchScore: 80,
      durabilityScore: 82,
      requiredTools: ["Staple gun (T50)", "Drill/driver", "Pocket hole jig", "Circular saw or store cuts", "Serrated knife or electric carving knife (foam)"],
      pros: [
        "HD36 seat foam - the same spec a good upholstery shop would use",
        "Upholstery-weight boucle-look fabric with pattern-matching margin",
        "Soft-close lid stay and ventilation gaps - kid-safe storage",
        "Batting-wrapped body for the soft rounded look of the reference",
      ],
      cons: ["Fabric cost is real - the bolt is a third of the budget", "Corner folds take patience and a practice run on scrap"],
      bestFor: "The best look-per-dollar version - what this plan's steps describe",
      compromises: ["Plain wrap instead of sewn channel tufting", "Staple construction instead of sewn covers (invisible in the result)"],
      recommendationReason: "Correct foam and fabric where they matter, simple construction where it does not show.",
      recommended: true,
    },
    {
      id: "path_closest",
      name: "closest_match",
      label: "Closest Match",
      estimatedCostLow: 450,
      estimatedCostHigh: 680,
      estimatedTime: "2-3 weekends (18-26 hours) + sewing",
      difficulty: "Intermediate (sewing machine required)",
      visualMatchScore: 90,
      durabilityScore: 86,
      requiredTools: ["Everything in Balanced", "Sewing machine with heavy needle", "Zipper foot for piping"],
      pros: ["Sewn channel-tufted lid cover matches the high-end look exactly", "Piped edges and a zippered lid cover you can dry-clean", "Premium performance boucle at 30,000+ double rubs"],
      cons: ["Sewing channels in thick fabric is genuinely intermediate work", "Nearly doubles cost and time"],
      bestFor: "Sewing-machine owners chasing the exact catalog look",
      compromises: ["Time and the sewing learning curve"],
    },
  ],
  recommendedPathReason:
    "Balanced puts the money where hands and eyes verify it - HD36 foam and real upholstery fabric - while keeping construction at the staple-gun level a first-timer can execute crisply. The channel-tufted look is a fabric-and-sewing upgrade later; the box underneath would not change.",
  designSimplifier: {
    difficultOriginalDetails: [
      { detail: "Sewn channel tufting on the lid", whyDifficult: "Requires a sewing machine, walking foot or careful feed control, and confidence sewing 4+ layers of thick fabric in straight parallel lines." },
      { detail: "Piped (welted) edges", whyDifficult: "Piping needs bias-cut strips, a zipper foot, and corner easing - classic intermediate sewing." },
      { detail: "Invisible fabric joins on a 48 in. front face", whyDifficult: "Factories use 54 in. goods sewn to pattern; we lay out the wrap so the only join lands on a back corner." },
    ],
    simplifications: [
      { original: "Sewn channel-tufted lid", simplified: "Smooth plain-wrapped lid over 2 in. HD36 + dacron", fidelityImpact: "Loses the channel lines; keeps the thick soft silhouette. From across the room the mass and fabric read the same." },
      { original: "Piped edge details", simplified: "Batting-rounded edges with tight corner folds", fidelityImpact: "Cleaner-modern rather than tailored-traditional; matches most current references anyway." },
      { original: "Sewn fitted cover", simplified: "Staple-wrapped upholstery, joins hidden at back corners and under the base", fidelityImpact: "Zero visible difference when the folds are done per the mini-lesson." },
    ],
    preservedElements: ["48 x 18 footprint and seat height", "Thick padded lid profile", "Boucle-look texture", "Storage function with a safe lid", "Floor shadow line from real legs"],
    changedElements: ["Channel tufting becomes a smooth wrap", "Sewn cover becomes stapled wrap"],
    removedElements: ["Piping/welting", "Zippered removable cover (see Closest Match path)"],
    fidelityLossSummary: "You lose the stitched detailing up close; you keep the shape, the texture, the thickness, and the function. Most guests will clock the fabric, not the seams.",
    rationale: "Every simplification removes a sewing-machine dependency while keeping the specs (foam density, fabric weight) that determine how the bench feels and lasts.",
  },
  minimumViableDupe: {
    summary: "A fixed-top padded bench: store-cut plywood box, 1 in. foam + batting on top only, budget fabric wrap, screw-on feet. The 'do we like a bench here' version.",
    mustPreserveElements: ["48 x 18 footprint", "Padded top with rounded edges", "Light nubby fabric tone"],
    canSimplifyElements: ["Fixed top instead of hinged", "Batting-only on the sides", "Dome feet instead of legs"],
    canRemoveElements: ["Storage compartment", "Soft-close hardware", "Dust cover bottom"],
    constructionApproach: "Store-cut panels, butt-jointed with screws, top glued and screwed down, then one continuous fabric wrap stapled underneath.",
    estimatedCostLow: 140,
    estimatedCostHigh: 220,
    estimatedTime: "1 weekend (6-8 hours)",
    fidelityTradeoff: "About two-thirds of the look for half the cost; no storage and a firmer, thinner seat.",
  },
  dimensions: [
    { label: "Overall width", value: "48 in.", source: "standard", confidence: 70 },
    { label: "Overall depth", value: "18 in.", source: "standard", confidence: 70 },
    { label: "Seat height", value: "~19 in.", source: "standard", confidence: 75 },
    { label: "Box height (plywood)", value: "12 in.", source: "estimated", confidence: 90 },
    { label: "Lid build-up (ply + foam)", value: "2-3/4 in.", source: "estimated", confidence: 90 },
    { label: "Leg height", value: "4-1/2 in.", source: "estimated", confidence: 80 },
    { label: "Interior storage", value: "~44 x 15 x 10-1/2 in.", source: "estimated", confidence: 85 },
  ],
  materials: [
    {
      name: "Birch plywood",
      category: "Sheet goods",
      quantity: "1 sheet",
      specification: "3/4 in. x 4 ft x 8 ft, B/BB or better (flatness matters more than face grade - it all gets covered)",
      purpose: "The entire box: front, back, sides, bottom, lid",
      estimatedCostLow: 55,
      estimatedCostHigh: 70,
      budgetAlternative: "Sanded pine ply or even 5/8 in. OSB for a painted-interior budget box (saves ~$20)",
      premiumAlternative: "Prefinished maple ply so the storage interior needs zero finishing (+$25)",
      notes: "Get the store to make the three rip cuts per the cut sheet if you have no saw - the tolerances here are forgiving.",
    },
    {
      name: "Hardboard / 1/4 in. plywood panel",
      category: "Sheet goods",
      quantity: "1 handy panel (2 x 4 ft)",
      specification: "1/4 in. hardboard or plywood project panel",
      purpose: "Lid liner to hide staples inside the storage box (optional but tidy)",
      estimatedCostLow: 12,
      estimatedCostHigh: 18,
      budgetAlternative: "Skip it and staple neatly - purely cosmetic inside the box",
    },
    {
      name: "High-density upholstery foam",
      category: "Upholstery",
      quantity: "1 piece",
      specification: '2 in. x 24 in. x 72 in. HD36 (1.8 lb density / 36 ILD) - sold as "high density firm seat foam"',
      purpose: "The seat pad on the lid; the difference between furniture and a padded board",
      estimatedCostLow: 45,
      estimatedCostHigh: 60,
      budgetAlternative: "Watch the craft-store 40-50% foam coupon cycle - same product, big swing",
      premiumAlternative: "2-1/2 in. HD36 with a 1/2 in. memory-foam topper for a plusher sit (+$30)",
      notes: "Cut with an electric carving knife or long serrated bread knife - a razor drags and tears. Cut 1/4 in. oversize so the fabric compresses it slightly for a tight look.",
    },
    {
      name: "Dacron upholstery batting",
      category: "Upholstery",
      quantity: "5 yd roll",
      specification: "27 in. wide bonded polyester upholstery batting, medium loft (roughly 3/4 oz)",
      purpose: "Wraps the foam and the box - it rounds edges, hides plywood ridges, and lets fabric slide during stretching",
      estimatedCostLow: 15,
      estimatedCostHigh: 22,
      notes: "Never staple fabric straight to plywood on a visible face; batting is what makes it look upholstered instead of wrapped.",
    },
    {
      name: "Upholstery fabric",
      category: "Fabric",
      quantity: "2.5 yd",
      specification: "54 in. wide boucle-look upholstery weight, 15,000+ double rubs (Wyzenbeek), polyester or poly-blend",
      purpose: "Every visible surface; the entire look lives here",
      estimatedCostLow: 45,
      estimatedCostHigh: 88,
      budgetAlternative: "Mid-weight basketweave from the clearance wall ($10-14/yd) - acceptable, pills sooner",
      premiumAlternative: "Performance boucle at 30,000+ double rubs with stain finish ($35-50/yd) - the kids-and-pets answer",
      notes: "Check the rub count on the bolt-end label. Buy 2.5 yd, not 2: the extra half yard is corner-practice and pattern-matching insurance.",
    },
    {
      name: "Cambric dust cover",
      category: "Fabric",
      quantity: "1 yd",
      specification: "Black non-woven cambric (upholstery bottom cloth), 36+ in. wide",
      purpose: "Covers the raw underside like factory furniture; costs almost nothing, reads pro",
      estimatedCostLow: 5,
      estimatedCostHigh: 8,
    },
    {
      name: "Wood legs, tapered",
      category: "Legs & hardware",
      quantity: "4 + mounting plates",
      specification: "4-1/2 in. solid wood tapered legs with 5/16 in. hanger bolts + angled or straight top plates",
      purpose: "The floor shadow line; also what keeps fabric off the floor",
      estimatedCostLow: 32,
      estimatedCostHigh: 48,
      budgetAlternative: "1-1/2 in. screw-on dome feet ($8) - loses the shadow line",
      premiumAlternative: "Turned oak or walnut legs from an online leg shop (+$30-60)",
    },
    {
      name: "Spray adhesive",
      category: "Adhesive",
      quantity: "1 can",
      specification: "3M Super 77 or foam-rated spray adhesive, 13+ oz",
      purpose: "Tacking foam to the lid and batting to foam so nothing shifts during stretching",
      estimatedCostLow: 12,
      estimatedCostHigh: 16,
      notes: "Spray both surfaces, wait 30-60 seconds until tacky, then join - instant grab, no soak-through.",
    },
    {
      name: "Wood glue",
      category: "Adhesive",
      quantity: "1 bottle, 8 oz",
      specification: "Titebond II or equivalent PVA",
      purpose: "Box joints alongside the screws",
      estimatedCostLow: 6,
      estimatedCostHigh: 8,
    },
    {
      name: "Leg finish",
      category: "Finish",
      quantity: "1 half pint",
      specification: "Danish oil (natural) or a sample pot of matte black paint, depending on the reference colorway",
      purpose: "The only finishing in the whole build - the legs",
      estimatedCostLow: 9,
      estimatedCostHigh: 14,
    },
  ],
  materialSwaps: [
    {
      originalMaterial: "Boucle-look polyester upholstery fabric",
      alternativeMaterial: "Performance weave (Crypton-type or high-rub polyester)",
      costImpact: "higher",
      durabilityImpact: "higher",
      visualMatchImpact: "similar",
      difficultyImpact: "similar",
      pros: ["Survives kids, pets, and spilled juice", "Wipeable stain finish", "Higher rub counts last a decade"],
      cons: ["$10-20/yd more", "Slightly flatter texture than true boucle loops"],
      notes: "The default answer for households with children - the reference look barely changes.",
    },
    {
      originalMaterial: "2 in. HD36 foam",
      alternativeMaterial: "1 in. economy foam + extra batting",
      costImpact: "lower",
      durabilityImpact: "lower",
      visualMatchImpact: "lower",
      difficultyImpact: "easier",
      pros: ["Saves $25-35", "Fine for a rarely-sat display bench"],
      cons: ["Bottoms out under daily sitting within months", "Loses the thick-lid silhouette that sells the look"],
      notes: "Only for the Minimum Viable Dupe. If people will sit, buy the HD36.",
    },
    {
      originalMaterial: "Birch plywood box",
      alternativeMaterial: "Pre-made unfinished storage bench carcass (online)",
      costImpact: "higher",
      durabilityImpact: "similar",
      visualMatchImpact: "similar",
      difficultyImpact: "easier",
      pros: ["Zero cutting or box joinery - straight to upholstery"],
      cons: ["$60-100 more than a sheet of ply", "Sizes rarely match the reference exactly"],
      notes: "A legitimate shortcut if the woodworking half intimidates you more than the fabric half.",
    },
  ],
  hardware: [
    {
      name: "Pocket-hole screws",
      category: "Fasteners",
      quantity: "1 box (100)",
      specification: "#8 x 1-1/4 in. coarse-thread washer-head",
      purpose: "Box corner joints (invisible inside the storage compartment)",
      estimatedCostLow: 9,
      estimatedCostHigh: 12,
    },
    {
      name: "Wood screws",
      category: "Fasteners",
      quantity: "1 box (100)",
      specification: "#8 x 1-1/4 in. flat-head, star drive",
      purpose: "Bottom panel, leg plates, corner blocks",
      estimatedCostLow: 8,
      estimatedCostHigh: 12,
    },
    {
      name: "T50 staples",
      category: "Upholstery",
      quantity: "2 boxes (1,250 ct)",
      specification: '3/8 in. for fabric layers, 1/2 in. for batting into ply edges - both T50 crown',
      purpose: "Every upholstery attachment in the build",
      estimatedCostLow: 8,
      estimatedCostHigh: 12,
      notes: "If staples sit proud, tap them flush with a small hammer - proud staples telegraph through fabric on edges.",
    },
    {
      name: "Piano hinge",
      category: "Lid hardware",
      quantity: "1",
      specification: "1-1/16 in. open width x 48 in. continuous (piano) hinge, nickel, with screws",
      purpose: "Full-length lid attachment - distributes load and never sags like two butt hinges",
      estimatedCostLow: 14,
      estimatedCostHigh: 22,
    },
    {
      name: "Soft-close lid support",
      category: "Lid hardware",
      quantity: "1 (or 2 for 48 in. lids)",
      specification: "Soft-down / soft-close lid stay rated ~8-10 lb lids (e.g. toy-box safety stay)",
      purpose: "REQUIRED with kids: the lid lowers slowly instead of slamming on fingers",
      estimatedCostLow: 12,
      estimatedCostHigh: 18,
      notes: "Mount per the stay's template AFTER upholstery, through the fabric, into the ply.",
    },
    {
      name: "Leg mounting plates",
      category: "Legs & hardware",
      quantity: "4",
      specification: "5/16 in. threaded top plates (straight), with #10 x 3/4 in. screws",
      purpose: "Accept the legs' hanger bolts through the upholstered bottom face",
      estimatedCostLow: 8,
      estimatedCostHigh: 12,
      notes: "Often bundled with the legs - check before buying separately.",
    },
  ],
  tools: [
    { name: "Staple gun, T50", required: true, category: "Upholstery", purpose: "All fabric and batting attachment", owned: false, estimatedCostIfBuying: "$25-40 manual; $60+ electric if your hands tire fast", beginnerNote: "Practice 20 staples into scrap ply first - full-body-weight squeeze, gun pressed firmly down." },
    { name: "Drill/driver", required: true, category: "Power tool", purpose: "Pocket holes, box screws, hinge, legs", owned: true },
    { name: "Circular saw or store panel saw", required: true, category: "Cutting", purpose: "Breaking the sheet into box panels", owned: false, substitute: "The store panel saw does every cut in this plan within tolerance", estimatedCostIfBuying: "$0 with store cuts" },
    { name: "Pocket hole jig", required: false, category: "Joinery jig", purpose: "Clean hidden box joints", owned: false, substitute: "Butt joints with glue + screws through the faces work fine - everything is covered by fabric", estimatedCostIfBuying: "$25-45" },
    { name: "Electric carving knife or long serrated knife", required: true, category: "Upholstery", purpose: "Clean square foam cuts", owned: false, substitute: "A $10 bread knife with long smooth strokes; never a razor", estimatedCostIfBuying: "$15-25 (thrift stores are full of electric carving knives)" },
    { name: "Heavy scissors / rotary cutter", required: true, category: "Fabric", purpose: "Fabric and batting cutting", owned: false, estimatedCostIfBuying: "$12-20" },
    { name: "Staple lifter / flat screwdriver + pliers", required: true, category: "Upholstery", purpose: "Pulling the staples you will inevitably redo", owned: false, estimatedCostIfBuying: "$8-12" },
    { name: "Tape measure + straightedge", required: true, category: "Layout", purpose: "Panel layout and fabric cutting lines", owned: true },
  ],
  toolAwareNotes: [
    {
      missingTool: "Circular saw",
      impact: "No way to break down the plywood sheet at home",
      workaround: "The store cut sheet lists every cut - all are simple rips and crosscuts a panel saw does in five minutes. Tolerances here are forgiving (+/- 1/8 in. is fine everywhere except the lid, which you should have them cut last with a fresh measure).",
      workaroundType: "store_cut",
    },
    {
      missingTool: "Pocket hole jig",
      impact: "Box joints would show screw heads on outside faces",
      workaround: "Screw through the outside faces anyway - every face gets wrapped in batting and fabric. Countersink so heads sit flush and nothing telegraphs.",
      workaroundType: "technique_change",
    },
  ],
  buildReadiness: {
    score: 82,
    readyStatus: "mostly_ready",
    missingTools: ["Staple gun ($25-40) - the one genuinely required purchase", "Foam knife (a bread knife works)"],
    missingMaterials: ["Everything on the shopping list"],
    skillGaps: ["First-time corner folds: practice on scrap batting + fabric offcut before the real lid corners"],
    workspaceConcerns: ["Fabric wants a clean floor or table - sawdust in boucle loops is forever", "Do all cutting/sanding before the fabric comes out of the bag"],
    budgetConcerns: ["Fabric is the swing line: $45 on sale to $88 for performance weave"],
    safetyConcerns: ["Soft-close lid stay is non-negotiable around small children"],
    recommendation: "Shop, then build the box weekend one and upholster weekend two. Keep the wood phase and fabric phase on separate days - dust and upholstery do not mix.",
  },
  difficultyBreakdown: {
    overall: "beginner",
    cuttingAccuracy: "Low: box tolerances are +/- 1/8 in.; only the lid wants a careful fit (1/8 in. gap at hinge side)",
    assembly: "Easy: glue-and-screw box, hinge with pre-drilled holes",
    joinery: "Easy: pocket screws or through-screws - all hidden under fabric",
    finishMatching: "Easy-moderate: fabric selection is taste, not technique; legs get a wipe-on oil",
    toolComplexity: "Low: staple gun and drill",
    physicalHandling: "Easy: heaviest lift is a half sheet of plywood",
    safetyRisk: "Low: standard cutting/drilling care plus the lid pinch-point hardware",
    timeCommitment: "12-16 hours across 1-2 weekends",
    repairability: "Excellent: stapled covers come off with a staple lifter; recover the whole bench in an afternoon someday",
    beginnerTolerance: "High - batting hides small sins, and staples are removable. The most forgiving furniture category there is.",
    notes: ["The skill curve lives entirely in the four lid corners. The mini-lesson plus one practice corner beats any amount of reading."],
  },
  cutList: [
    { partName: "Front / back panel", quantity: 2, material: "3/4 in. birch ply", dimensions: "48 x 12 in." },
    { partName: "Side panel", quantity: 2, material: "3/4 in. birch ply", dimensions: "16-1/2 x 12 in." },
    { partName: "Bottom panel", quantity: 1, material: "3/4 in. birch ply", dimensions: "46-1/2 x 16-1/2 in.", notes: "Sits inside the four walls, flush with their bottom edges." },
    { partName: "Lid", quantity: 1, material: "3/4 in. birch ply", dimensions: "48 x 18 in.", notes: "Overhangs the box 3/4 in. at front and sides once upholstered - intentional." },
    { partName: "Leg block", quantity: 4, material: "3/4 in. birch ply offcut", dimensions: "5 x 5 in.", notes: "Doubles the bottom thickness where leg plates screw in." },
    { partName: "Lid liner (optional)", quantity: 1, material: "1/4 in. hardboard", dimensions: "44 x 14-1/2 in.", notes: "Hides lid staples inside the box." },
    { partName: "Seat foam", quantity: 1, material: "2 in. HD36 foam", dimensions: "48-1/4 x 18-1/4 in.", notes: "1/4 in. oversize so the wrap compresses it tight." },
    { partName: "Lid fabric", quantity: 1, material: "54 in. upholstery fabric", dimensions: "58 x 28 in.", notes: "Lid + foam wrap + 4 in. stapling allowance per side." },
    { partName: "Body wrap fabric", quantity: 1, material: "54 in. upholstery fabric", dimensions: "2 pieces ~70 x 17 in.", notes: "Wraps meet at the two back corners." },
  ],
  cutOptimizationPlans: [
    {
      material: "3/4 in. birch plywood",
      sourceSize: "4 ft x 8 ft (1 sheet)",
      cuts: [
        { partName: "Lid", quantity: 1, dimensions: "48 x 18 in.", precision: "finish", notes: "From the 18 in. rip - the only cut where accuracy matters, cut it first." },
        { partName: "Bottom panel", quantity: 1, dimensions: "46-1/2 x 16-1/2 in.", precision: "rough", notes: "From the rest of the 18 in. rip, trimmed down." },
        { partName: "Front / back panel", quantity: 2, dimensions: "48 x 12 in.", precision: "rough", notes: "One from each 12 in. rip." },
        { partName: "Side panel", quantity: 2, dimensions: "16-1/2 x 12 in.", precision: "rough", notes: "From the 12 in. rip remainders." },
        { partName: "Leg blocks", quantity: 4, dimensions: "5 x 5 in.", precision: "rough", notes: "Any offcut." },
      ],
      estimatedWastePercent: 26,
      grainDirectionNotes: ["Grain direction is irrelevant - every face gets covered. Chase yield, not looks."],
      sequenceNotes: [
        "Rip the sheet lengthwise at 18 in., then 12 in., then 12 in. (three rips).",
        "Crosscut the 18 in. strip at 48 in. for the lid; trim the remainder for the bottom.",
        "Crosscut each 12 in. strip at 48 in. for front/back; sides come from what remains.",
      ],
    },
  ],
  storeCutSheet: {
    storeName: "Home Depot",
    intro:
      "Five cuts on one sheet - well inside the free-cut zone. These are box parts hidden under fabric, so panel-saw tolerance is fine everywhere. Ask for the LID cut (48 x 18) first while the blade is tracking a fresh factory edge.",
    requests: [
      {
        material: "3/4 in. birch plywood (1 sheet)",
        buySize: "4 ft x 8 ft",
        requestedCuts: [
          { label: "Lid + bottom strip", cutTo: "Rip at 18 in. (full length)", finalTrimAtHome: false, notes: "Then crosscut at 48 in. - the 48 x 18 piece is the finished lid." },
          { label: "Front/back strip 1", cutTo: "Rip remaining piece at 12 in.", finalTrimAtHome: false },
          { label: "Front/back strip 2", cutTo: "Rip again at 12 in.", finalTrimAtHome: false },
          { label: "Crosscuts", cutTo: "Crosscut both 12 in. strips at 48 in.", oversizedBy: "none needed", finalTrimAtHome: true, notes: "Side panels (16-1/2 x 12) can be cut at home with a jigsaw/circular saw, or ask for two more crosscuts." },
        ],
      },
    ],
    warnings: [
      "Measure the 48 x 18 lid piece before leaving - it is the one part where 1/4 in. of error shows in the final overhang.",
      "Panel saw tolerance is +/- 1/8 in.: fine for every part of this build.",
    ],
    homeTrimNotes: ["Trim the bottom panel to 46-1/2 x 16-1/2 at home after dry-fitting the box - actual interior beats theoretical interior."],
  },
  budgetBreakdown: {
    lines: [
      {
        category: "Lumber & sheet goods",
        items: [
          { name: "Birch plywood 3/4 in. 4x8", costLow: 55, costHigh: 70 },
          { name: "Hardboard 1/4 in. handy panel", costLow: 12, costHigh: 18 },
        ],
        subtotalLow: 67,
        subtotalHigh: 88,
      },
      {
        category: "Upholstery materials",
        items: [
          { name: "HD36 foam 2 x 24 x 72 in.", costLow: 45, costHigh: 60 },
          { name: "Dacron batting, 5 yd", costLow: 15, costHigh: 22 },
          { name: "Upholstery fabric, 2.5 yd", costLow: 45, costHigh: 88 },
          { name: "Cambric dust cover, 1 yd", costLow: 5, costHigh: 8 },
        ],
        subtotalLow: 110,
        subtotalHigh: 178,
      },
      {
        category: "Hardware & fasteners",
        items: [
          { name: "T50 staples 3/8 + 1/2 in.", costLow: 8, costHigh: 12 },
          { name: "Wood screws #8 x 1-1/4 (100)", costLow: 8, costHigh: 12 },
          { name: "Pocket-hole screws (100)", costLow: 9, costHigh: 12 },
          { name: "Piano hinge 48 in.", costLow: 14, costHigh: 22 },
          { name: "Soft-close lid stay", costLow: 12, costHigh: 18 },
          { name: "Legs (4) + mounting plates", costLow: 32, costHigh: 48 },
        ],
        subtotalLow: 83,
        subtotalHigh: 124,
      },
      {
        category: "Adhesives & finish",
        items: [
          { name: "Spray adhesive", costLow: 12, costHigh: 16 },
          { name: "Wood glue 8 oz", costLow: 6, costHigh: 8 },
          { name: "Leg finish (Danish oil or paint sample)", costLow: 9, costHigh: 14 },
        ],
        subtotalLow: 27,
        subtotalHigh: 38,
      },
      {
        category: "Safety gear",
        items: [
          { name: "Safety glasses + dust masks", costLow: 10, costHigh: 16 },
        ],
        subtotalLow: 10,
        subtotalHigh: 16,
      },
      {
        category: "Contingency",
        items: [{ name: "Fabric mis-cut buffer (~5%)", costLow: 0, costHigh: 26, optional: true }],
        subtotalLow: 0,
        subtotalHigh: 26,
      },
    ],
    materialsTotalLow: 297,
    materialsTotalHigh: 444,
    optionalToolsLow: 25,
    optionalToolsHigh: 40,
    grandTotalLow: 297,
    grandTotalHigh: 470,
    referencePrice: 1199,
    estimatedSavingsLow: 729,
    estimatedSavingsHigh: 902,
    confidence: 78,
    notes: [
      "Required categories sum to $297 (all low) / $444 (all high); grand total high $470 = $444 + $26 contingency.",
      "The staple gun ($25-40) is tracked as an optional tool, not in the grand total, per the tool-costs-excluded convention.",
      "Fabric is the volatile line: coupon cycles and clearance walls swing it 40 percent either way.",
    ],
  },
  shoppingListByDepartment: [
    {
      store: "Home Depot",
      department: "Lumber & Sheet Goods",
      items: [
        { name: "Birch plywood", quantity: "1 sheet", spec: "3/4 in. x 4 ft x 8 ft", estimatedCostLow: 55, estimatedCostHigh: 70, required: true, notes: "Get the 5 store cuts per the cut sheet." },
        { name: "Hardboard handy panel", quantity: "1", spec: "1/4 in. x 2 ft x 4 ft", estimatedCostLow: 12, estimatedCostHigh: 18, required: false, notes: "Lid liner - optional tidiness." },
      ],
    },
    {
      store: "Home Depot",
      department: "Hardware & Fasteners",
      items: [
        { name: "Piano hinge", quantity: "1", spec: "1-1/16 x 48 in. continuous, nickel", estimatedCostLow: 14, estimatedCostHigh: 22, required: true },
        { name: "Soft-close lid stay", quantity: "1-2", spec: "toy-box safety rated, ~8-10 lb lid", estimatedCostLow: 12, estimatedCostHigh: 18, required: true, notes: "Non-negotiable with kids in the house." },
        { name: "Wood screws", quantity: "1 box (100)", spec: "#8 x 1-1/4 in. star drive", estimatedCostLow: 8, estimatedCostHigh: 12, required: true },
        { name: "Pocket-hole screws", quantity: "1 box (100)", spec: "#8 x 1-1/4 in. coarse washer-head", estimatedCostLow: 9, estimatedCostHigh: 12, required: true },
        { name: "T50 staples", quantity: "2 boxes", spec: "3/8 in. and 1/2 in.", estimatedCostLow: 8, estimatedCostHigh: 12, required: true },
        { name: "Furniture legs + plates", quantity: "4 + 4", spec: "4-1/2 in. tapered wood, 5/16 hanger bolts", estimatedCostLow: 32, estimatedCostHigh: 48, required: true },
      ],
    },
    {
      store: "Home Depot",
      department: "Paint & Adhesives",
      items: [
        { name: "Spray adhesive", quantity: "1 can", spec: "3M Super 77 or foam-rated", estimatedCostLow: 12, estimatedCostHigh: 16, required: true },
        { name: "Wood glue", quantity: "1", spec: "8 oz PVA", estimatedCostLow: 6, estimatedCostHigh: 8, required: true },
        { name: "Danish oil or paint sample", quantity: "1", spec: "half pint, for legs", estimatedCostLow: 9, estimatedCostHigh: 14, required: true },
        { name: "Safety glasses + masks", quantity: "1 + 3", spec: "basic", estimatedCostLow: 10, estimatedCostHigh: 16, required: true },
      ],
    },
    {
      store: "Joann",
      department: "Upholstery & Fabric",
      items: [
        { name: "HD36 high-density foam", quantity: "1", spec: "2 x 24 x 72 in., 1.8 lb density", estimatedCostLow: 45, estimatedCostHigh: 60, required: true, notes: "Wait for the 40-50% foam coupon if you can." },
        { name: "Boucle-look upholstery fabric", quantity: "2.5 yd", spec: "54 in. wide, 15,000+ double rubs", estimatedCostLow: 45, estimatedCostHigh: 88, required: true, notes: "Check the bolt-end label for the rub count." },
        { name: "Dacron batting", quantity: "5 yd", spec: "27 in. bonded polyester, medium loft", estimatedCostLow: 15, estimatedCostHigh: 22, required: true },
        { name: "Cambric dust cover", quantity: "1 yd", spec: "black non-woven", estimatedCostLow: 5, estimatedCostHigh: 8, required: true },
      ],
    },
  ],
  projectTimeline: [
    {
      phase: "Shopping & box build",
      dayOrSession: "Weekend 1, Saturday",
      estimatedDuration: "4-5 hours including store runs",
      tasks: ["Buy lumber + hardware, get store cuts", "Fabric store run (or confirm the online order arrived)", "Assemble the box (Steps 2-4)", "Fit the lid and hinge dry (Step 5)"],
      notes: "Two stores: big-box for wood/hardware, fabric store for upholstery goods.",
    },
    {
      phase: "Sand, seal, legs",
      dayOrSession: "Weekend 1, Sunday",
      estimatedDuration: "2-3 hours",
      tasks: ["Ease every edge, sand the interior (Step 6)", "Finish the legs", "Vacuum the workspace completely - fabric phase starts next"],
      waitTime: "Leg finish dries overnight",
    },
    {
      phase: "Upholstery",
      dayOrSession: "Weekend 2, Saturday",
      estimatedDuration: "5-6 hours",
      tasks: ["Cut foam and batting (Step 7)", "Foam + batting onto the lid (Steps 8-9)", "Fabric layout and cutting (Step 10)", "Upholster the lid (Step 11)", "Upholster the body (Step 12)"],
      notes: "Clean hands, clean floor, no coffee cups near the cream fabric. Ask us how we know.",
    },
    {
      phase: "Assembly & finish",
      dayOrSession: "Weekend 2, Sunday",
      estimatedDuration: "2-3 hours",
      tasks: ["Hinge + lid stay through the fabric (Step 13)", "Cambric, leg plates, legs (Step 14)", "Final inspection"],
    },
  ],
  preBuildChecklist: [
    "Confirm the bench footprint in its spot with painter's tape - 48 x 18 in. plus knee room.",
    "Order fabric swatches FIRST if buying online; approve texture and tone in your room's light.",
    "Verify the foam spec on the label: HD or 1.8 lb density, 2 in. thick. 'Craft foam' is not it.",
    "Practice 20 staples into scrap ply; adjust your squeeze and gun pressure until they sit flush.",
    "Separate the build into a dust phase and a fabric phase - never both in one session.",
    "Check the lid stay's minimum lid weight rating against a ~9 lb upholstered lid.",
  ],
  steps: [
    {
      stepNumber: 1,
      title: "Confirm sizes and get the sheet cut",
      estimatedTime: "1 hour (store trip)",
      goal: "All box panels cut to the list, lid piece verified at 48 x 18",
      toolsNeeded: ["Tape measure"],
      materialsNeeded: ["Birch plywood sheet", "Store cut sheet"],
      instructions: [
        "At the panel saw, request the cuts in the printed order: 18 in. rip first, lid crosscut at 48 in. while the factory edge still guides the fence.",
        "Measure the lid piece (48 x 18) before you leave the cutting area - it is the only piece where 1/4 in. matters.",
        "Load sheet goods flat; a 12 in. strip flexed over a tailgate can snap.",
      ],
      qualityCheck: "Lid measures 48 x 18 within 1/8 in.; all strips present per the cut list.",
      commonMistake: "Letting the associate cut the 12 in. strips first - the fence re-set error then lands on your lid.",
      phase: "Box build",
    },
    {
      stepNumber: 2,
      title: "Drill pocket holes and dry-fit the box",
      estimatedTime: "45 minutes",
      goal: "Four walls that meet square with joints hidden inside",
      toolsNeeded: ["Pocket hole jig", "Drill/driver", "Speed square or framing square"],
      materialsNeeded: ["Front/back panels", "Side panels"],
      instructions: [
        "Drill three pocket holes along each vertical end of the two SIDE panels (jig set for 3/4 in. stock) - pockets face inward, hidden by the storage interior.",
        "Dry-clamp the box: sides captured between front and back, outside faces flush.",
        "Check both diagonals across the top opening; adjust until they match within 1/8 in.",
        "No jig? Skip the pockets and plan to screw through the front/back faces instead - fabric hides everything.",
      ],
      qualityCheck: "Diagonals within 1/8 in.; top edges flush all around.",
      commonMistake: "Pocketing the front/back panels instead of the sides - then the pockets face the room until fabric day.",
      relatedMiniLessons: ["ml_pocket_holes_bench"],
      phase: "Box build",
    },
    {
      stepNumber: 3,
      title: "Glue and screw the box together",
      estimatedTime: "45 minutes",
      goal: "A square, rigid four-wall box",
      toolsNeeded: ["Drill/driver", "Clamps", "Square"],
      materialsNeeded: ["Wall panels", "Wood glue", "Pocket or wood screws"],
      instructions: [
        "Glue both mating edges of one corner, clamp, check square, drive the screws. Repeat corner by corner.",
        "Re-check the diagonals after the last corner - clamps love to rack boxes out of square.",
        "Wipe glue squeeze-out inside with a damp rag now; sanding cured glue in a 12 in. deep box is miserable.",
      ],
      qualityCheck: "Box sits flat on the floor without rocking; diagonals match.",
      commonMistake: "Building on an un-flat garage floor and gluing a twist into the box. Assemble on the flattest surface you have.",
      phase: "Box build",
    },
    {
      stepNumber: 4,
      title: "Install the bottom and leg blocks",
      estimatedTime: "45 minutes",
      goal: "A structural floor that also anchors the legs",
      toolsNeeded: ["Drill/driver", "Countersink bit"],
      materialsNeeded: ["Bottom panel", "4 leg blocks", "Wood glue", "#8 x 1-1/4 screws"],
      instructions: [
        "Trim the bottom to the measured interior (target 46-1/2 x 16-1/2) and drop it in flush with the walls' bottom edges.",
        "Screw through the walls into the bottom edge every 8 in., countersunk.",
        "Glue and screw a 5 x 5 leg block under each corner of the bottom, inset 1 in. from each edge - legs bite into 1-1/2 in. of wood, not 3/4 in.",
        "Drill a 1/4 in. ventilation hole near each top corner of the back panel - storage boxes should never be airtight, especially around kids.",
      ],
      safetyNotes: ["The ventilation holes are a child-safety detail, not an option. They also let the box breathe so the interior never smells musty."],
      qualityCheck: "Bottom flush, no gaps at walls; blocks solid under each corner.",
      phase: "Box build",
    },
    {
      stepNumber: 5,
      title: "Fit the lid and hinge (dry run)",
      estimatedTime: "45 minutes",
      goal: "Lid aligned with even overhangs and hinge holes pre-drilled - BEFORE any fabric",
      toolsNeeded: ["Drill/driver", "3/32 in. bit"],
      materialsNeeded: ["Lid", "Piano hinge"],
      instructions: [
        "Set the lid on the box: flush at the back, 3/4 in. overhang at front and both sides (fabric thickness will visually tighten this).",
        "Center the piano hinge on the back top edge; mark and pre-drill every third hole into both lid and box back.",
        "Screw it on, open and close a few times, admire, then REMOVE the hinge - it reinstalls through the fabric at Step 13.",
        "Label the lid's back edge and box's back face so orientation never gets flipped later.",
      ],
      qualityCheck: "Lid closes with even overhangs; hinge screws bite firmly.",
      commonMistake: "Skipping this dry run and discovering at the end that the upholstered lid sits crooked - hinge holes are much harder to move through fabric.",
      phase: "Box build",
    },
    {
      stepNumber: 6,
      title: "Ease edges, sand, and finish the legs",
      estimatedTime: "1.5 hours + overnight dry",
      goal: "No sharp plywood edge anywhere fabric will stretch over; legs finished",
      toolsNeeded: ["Sanding block, 120 grit", "Rag for oil"],
      materialsNeeded: ["Assembled box + lid", "Legs", "Danish oil or paint"],
      instructions: [
        "Round every edge the fabric will wrap - especially the lid's top perimeter - to about a 1/8 in. radius with the 120 block. Sharp plywood edges saw through fabric from the inside over years.",
        "Sand the storage interior to 150 and knock down splinters; it stays bare wood (or give it one quick coat of leftover poly if you have any).",
        "Wipe Danish oil on the legs (or prime + paint for the black-leg colorway). Set aside to dry.",
        "Vacuum EVERYTHING. The dust phase of this project ends now.",
      ],
      safetyNotes: ["Dispose of oil-soaked rags spread flat outdoors to dry - balled oily rags can self-heat."],
      qualityCheck: "Run a nylon stocking over every wrapped edge - no snags.",
      phase: "Box build",
    },
    {
      stepNumber: 7,
      title: "Cut the foam and batting",
      estimatedTime: "30 minutes",
      goal: "Seat foam at 48-1/4 x 18-1/4 and batting pieces rough-cut for lid and body",
      toolsNeeded: ["Electric carving knife or serrated knife", "Marker", "Straightedge", "Scissors"],
      materialsNeeded: ["HD36 foam", "Dacron batting"],
      instructions: [
        "Mark the foam with a marker and straightedge; cut with long full-depth strokes, letting the serrations do the work - do not press down hard or the edge crowns.",
        "Cut foam 1/4 in. oversize (48-1/4 x 18-1/4): compression under the wrap gives the tight, expensive look.",
        "Rough-cut batting: one lid piece ~56 x 26 in., and body strips long enough to wrap each face with 2 in. spare.",
      ],
      qualityCheck: "Foam edges square, no scalloped saw marks deeper than 1/8 in.",
      commonMistake: "Cutting foam with a razor blade - it drags, tears, and leaves a ragged edge batting cannot fully hide.",
      relatedMiniLessons: ["ml_foam_batting"],
      phase: "Upholstery",
    },
    {
      stepNumber: 8,
      title: "Bond the foam to the lid",
      estimatedTime: "20 minutes",
      goal: "Foam centered and locked to the lid so nothing shifts during stretching",
      toolsNeeded: ["Spray adhesive"],
      materialsNeeded: ["Lid", "Seat foam"],
      instructions: [
        "Outdoors or with big ventilation: spray adhesive on the lid top AND the foam bottom, wait 30-60 seconds until tacky-not-wet.",
        "Hover, center (the foam overhangs 1/8 in. all around), then commit - contact adhesive grabs on touch.",
        "Press firmly across the whole area for 30 seconds.",
      ],
      safetyNotes: ["Spray adhesive fumes are the strongest chemical exposure in this build - outdoors or door-open ventilation, and keep kids away during spraying."],
      qualityCheck: "Even 1/8 in. foam overhang on all four sides; no rocking when pressed.",
      phase: "Upholstery",
    },
    {
      stepNumber: 9,
      title: "Wrap the lid in batting",
      estimatedTime: "30 minutes",
      goal: "A softly rounded dome ready for fabric - this is where the 'upholstered' look is born",
      toolsNeeded: ["Staple gun (1/2 in. staples)", "Scissors"],
      materialsNeeded: ["Lid + foam", "Batting"],
      instructions: [
        "Center the lid foam-down on the batting piece.",
        "Pull the batting up and over each edge - snug, not stretched hard - and staple to the lid underside about 1-1/2 in. in from the edge, center of each side first, then work toward corners every 3 in.",
        "At corners, cut away bulk so the batting overlaps once, not three times, and staple flat.",
        "Trim excess batting past the staple lines.",
      ],
      qualityCheck: "The lid's top edges now look rounded, not square, and the batting has no hard wrinkles on the show face.",
      commonMistake: "Over-stretching the batting until it tears or compresses the foam edge flat - batting is a blanket, not a drum skin.",
      relatedMiniLessons: ["ml_foam_batting"],
      phase: "Upholstery",
    },
    {
      stepNumber: 10,
      title: "Lay out and cut the fabric",
      estimatedTime: "45 minutes",
      goal: "Lid piece and body pieces cut with the weave running the same direction on every face",
      toolsNeeded: ["Scissors or rotary cutter", "Straightedge", "Chalk or fabric marker"],
      materialsNeeded: ["Upholstery fabric, 2.5 yd"],
      instructions: [
        "Iron or steam the fabric flat first - creases stapled in are creases forever.",
        "Mark the weave/nap direction on the back of the bolt with chalk arrows before cutting anything.",
        "Cut the lid piece 58 x 28 in. (lid + wrap + 4 in. stapling allowance per side).",
        "Cut two body pieces ~70 x 17 in. so each wraps from one back corner around the front to the other back corner - joins land only on back corners.",
        "Save every offcut - corner practice and future repairs.",
      ],
      qualityCheck: "All chalk arrows point the same way; pieces verified against their faces with 3+ in. spare everywhere.",
      commonMistake: "Cutting exact-size 'to save fabric.' You cannot staple what you cannot grip - the allowance IS the handle.",
      phase: "Upholstery",
    },
    {
      stepNumber: 11,
      title: "Upholster the lid",
      estimatedTime: "1.5 hours",
      goal: "A drum-tight top with four clean corners - the money step",
      toolsNeeded: ["Staple gun (3/8 in. staples)", "Staple lifter", "Scissors"],
      materialsNeeded: ["Batted lid", "Lid fabric piece"],
      instructions: [
        "Fabric face-down on a clean table, lid centered face-down on it. Check the weave arrows run lid-lengthwise.",
        "Staple the CENTER of each side in this order: front, back (pulling snug), left, right - a cross of tension that centers everything.",
        "Work from centers toward corners, alternating sides, staples every 2 in., pulling with a flat palm-drag (not fingertip pinches which make scallops). Stop 3 in. from every corner.",
        "Corners: pull the point diagonally over the corner and tack; fold each side into a single tucked pleat facing the bench's short ends and staple. One practice corner on scrap first - it is a hand skill, not a diagram skill.",
        "Flip and inspect under raking light: any scallops or drifted weave, pull that section's staples with the lifter and re-do. Staples are free; wrinkles are permanent.",
        "Trim excess and optionally screw the hardboard liner over the staple field.",
      ],
      qualityCheck: "Weave lines run parallel to the lid edges; no scallops between staples; both front corners fold the same direction.",
      commonMistake: "Chasing maximum tension. This fabric wants snug-plus-a-little; over-stretching distorts boucle loops into stripes.",
      relatedMiniLessons: ["ml_corner_folds"],
      phase: "Upholstery",
    },
    {
      stepNumber: 12,
      title: "Upholster the box body",
      estimatedTime: "1.5 hours",
      goal: "A wrapped body with joins hidden on the back corners and clean top/bottom edges",
      toolsNeeded: ["Staple gun", "Scissors", "Straightedge"],
      materialsNeeded: ["Box", "Batting strips", "2 body fabric pieces", "Spray adhesive"],
      instructions: [
        "Light spray-tack batting to all four outside faces; trim flush at top and bottom edges (batting stops AT the edges here - bulk over box edges fights the lid fit).",
        "Start piece 1 at a back corner: fold its starting edge under 1/2 in. and staple that fold vertically down the corner, every 2 in.",
        "Wrap around the side, across the front, to the far back corner, smoothing as you go; staple the top edge over into the box interior and the bottom edge onto the box underside.",
        "End piece 1 by folding its edge under and stapling down the second back corner. Piece 2 covers the back face between the two folded corner seams.",
        "Keep the fabric weave parallel to the box top edge the whole way - check every 12 in. against the edge, not by eye.",
      ],
      qualityCheck: "Front face is seamless; the two joins sit exactly on back corners as tight vertical folds.",
      commonMistake: "Letting the weave drift downhill as you wrap - by the far corner the texture visibly slopes. Check against the top edge as you go.",
      phase: "Upholstery",
    },
    {
      stepNumber: 13,
      title: "Reinstall the hinge and fit the lid stay",
      estimatedTime: "45 minutes",
      goal: "A working lid that opens smoothly and CANNOT slam shut",
      toolsNeeded: ["Drill/driver", "Awl or 3/32 bit"],
      materialsNeeded: ["Piano hinge", "Soft-close lid stay", "Upholstered lid + box"],
      instructions: [
        "Find the pre-drilled hinge holes through the fabric with an awl (they are where you left them in Step 5).",
        "Screw the hinge to the box back first, then to the lid, using the original holes.",
        "Mount the soft-close lid stay per its paper template on the side wall interior and lid underside.",
        "Test: the lid should fall from fully open and land silently over 3+ seconds. Adjust the stay's tension screw until it does.",
      ],
      safetyNotes: ["Do not skip or defer the lid stay. A 9 lb upholstered lid free-falling on small fingers is this project's one real hazard, and an $85 part-and-labor emergency room visit costs more than five stays."],
      qualityCheck: "Slow, silent close from any height; lid aligned with even reveals.",
      phase: "Assembly",
    },
    {
      stepNumber: 14,
      title: "Cambric, legs, and final inspection",
      estimatedTime: "45 minutes",
      goal: "A finished underside, legs on, bench in service",
      toolsNeeded: ["Staple gun", "Drill/driver", "Scissors"],
      materialsNeeded: ["Cambric", "Leg plates + legs", "Felt pads"],
      instructions: [
        "Staple cambric over the entire underside, edges folded under, staples every 3 in. - cut small Xs where the leg blocks sit.",
        "Screw the four leg plates to the leg blocks through the cambric; thread on the legs.",
        "Stand it up, press-test for wobble, and stick a felt pad on each foot.",
        "Final pass: trim any fabric whiskers with sharp scissors, vacuum the boucle with an upholstery brush attachment.",
      ],
      qualityCheck: "No wobble; even stance; nothing raw visible even when tipped over.",
      commonMistake: "Overtightening legs into the plates until the hanger bolt strips the leg - snug plus a quarter turn.",
      phase: "Assembly",
    },
  ],
  diagrams: [
    {
      id: "dg_bench_exploded",
      title: "Box exploded view",
      type: "ascii",
      description: "How the six plywood parts and legs stack: lid over the four-wall box, bottom captured inside, leg blocks under the corners.",
      ascii: `            ________________________________
           /                               /|   LID 48 x 18
          /______________________________ / |   (foam + fabric above)
          |  =========== hinge =========  |     <- piano hinge, back edge
   ________________________________
  /       FRONT 48 x 12           /|
 /_______________________________/ |            SIDES 16-1/2 x 12
 |                               | |            captured between
 |   interior ~44 x 15 x 10.5    | |            front and back
 |_______________________________|/
     [==]                   [==]                <- leg blocks 5 x 5
      /\\                     /\\                 <- tapered legs 4-1/2 in.`,
      caption: "Every joint is hidden by fabric - build for square, not for pretty.",
    },
    {
      id: "dg_corner_fold",
      title: "Lid corner fold sequence",
      type: "ascii",
      description: "The three-move corner: diagonal pull, side pleats folded to the short ends, staple through all layers.",
      ascii: `   1) pull point         2) fold pleats        3) staple
      diagonally            toward short          underneath
         ____                  ____                 ____
        /    |                |    |               |    |
   ~~~~/     |            ~~~ |    |            ***|    |
  fabric     |             pleat -> |            *** = staples
   corner    |            single fold,          through folded
   over lid  |            not bunched           layers only`,
      caption: "One tucked pleat per corner side. If a corner has three folds, pull the staples and start again - staples are free.",
    },
    {
      id: "dg_fabric_layout",
      title: "Fabric cutting layout",
      type: "description",
      description:
        "On 2.5 yd (90 in.) of 54 in. fabric: the lid piece (58 x 28 in.) comes off one end, cut with its length along the bolt so the weave runs the lid's long way. The two body pieces (about 70 x 17 in. each) come off the remainder, both cut in the same direction so the nap matches all the way around. The leftover strip yields corner practice pieces and a spare patch to store under the bench.",
      caption: "Chalk-mark the nap direction arrows on the fabric back BEFORE the first cut.",
    },
  ],
  finishGuide: {
    referenceFinishDescription:
      "The 'finish' here is the fabric: a light cream boucle-look weave with visible loops and a soft matte hand, over softly rounded edges. Legs are natural pale wood or matte black depending on colorway.",
    confidence: 80,
    recommendedFinishSystem: [
      "Fabric: upholstery-weight boucle-look polyester, 15,000+ double rubs - texture over sheen",
      "Apply a fabric protector spray (Scotchgard-type) BEFORE first use, two light coats, outdoors",
      "Legs: two wiped coats of Danish oil (natural colorway) or primer + matte black enamel (black colorway)",
      "Storage interior: bare sanded wood, or one coat of water-based poly if you will store linens",
    ],
    budgetOption: ["Clearance-wall basketweave in a cream tone + protector spray", "Legs in leftover paint from any previous project"],
    premiumOption: ["Performance boucle (30,000+ rubs, stain-release finish) - skip the protector spray, it is built in", "Solid oak or walnut legs with hardwax oil"],
    stainPaintOptions: [
      { name: "Danish oil, natural", type: "penetrating oil (legs)", note: "Two wipe-on coats; warm pale tone that matches light-wood colorways." },
      { name: "Matte black enamel + primer", type: "paint (legs)", note: "For the black-leg reference look; two thin coats over primer." },
      { name: "Fabric protector spray", type: "textile treatment", note: "Two light coats before first use; reapply yearly. Test on an offcut first for tone shift." },
    ],
    topcoatOptions: [
      { name: "Scotchgard Fabric & Upholstery Protector", note: "The standard; light coats, fully dry between." },
      { name: "None (performance fabric)", note: "Stain-release weaves ship with the protection woven in." },
    ],
    colorMatchingTips: [
      "Judge fabric swatches in the room where the bench lives, at morning and evening light - cream fabrics swing warm/cool dramatically.",
      "Boucle photographs lighter than it looks in hand; go half a shade lighter than your target photo.",
      "Match the leg tone to the nearest wood in the room, not to the fabric.",
    ],
    testBoardInstructions: [
      "Staple a fabric offcut over a batting scrap on plywood - your corner practice piece doubles as the protector-spray test.",
      "Spray half the sample, let cure 24 h, then drip water on both halves: beads on the treated half, soaks on the raw half.",
      "Check the treated half for any tone shift before spraying the bench.",
    ],
    commonProblems: [
      { problem: "Water spot on the cream fabric", fix: "Blot (never rub), then clean the WHOLE panel edge to edge with upholstery shampoo so there is no cleaning ring." },
      { problem: "Boucle loops snagged", fix: "Never cut a pulled loop flush - thread it to the back with a blunt needle. Cut loops unravel." },
      { problem: "Pilling in sitting zones", fix: "A battery fabric shaver every few months; normal for looped weaves, not a defect." },
    ],
    curingNotes: [
      "Protector spray: 24 h cure before sitting.",
      "Danish oil legs: dry overnight, full hardness in about a week - felt pads after 72 h.",
    ],
    applicationSteps: [
      "Vacuum the finished bench with the upholstery brush.",
      "Two light protector coats 1 hour apart, outdoors, sweeping passes from 10 in.",
      "Cure 24 h before first use.",
    ],
  },
  miniLessons: [
    {
      id: "ml_corner_folds",
      title: "Upholstery corner folds",
      skillCategory: "Upholstery",
      difficulty: "beginner",
      explanation:
        "A clean corner is one diagonal pull plus one tucked pleat per side - never a bunch of gathers. The fabric has to go somewhere; a fold DECIDES where, a bunch lets it decide for itself.",
      steps: [
        "Pull the fabric point diagonally over the corner and tack with one staple.",
        "Fold the left flap into a single pleat aligned with the bench's short end; crease it with your thumb; staple through the folded layers.",
        "Repeat with the right flap. Both pleats on a bench face the short ends so they are invisible from the front.",
        "Trim the trapped bulk inside the fold if the pleat sits proud.",
      ],
      commonMistakes: ["Three or four small gathers instead of one fold (reads homemade instantly)", "Corner folds facing random directions - decide the direction rule before the first corner"],
    },
    {
      id: "ml_foam_batting",
      title: "Foam and batting basics",
      skillCategory: "Upholstery",
      difficulty: "beginner",
      explanation:
        "Foam gives the shape and support; batting rounds the edges, hides irregularities, and lets fabric slide during stretching instead of grabbing the foam. Skipping batting is the #1 tell of first-timer upholstery - fabric straight over foam shows every foam edge as a hard line.",
      steps: [
        "Buy seat foam by density (1.8 lb / HD36 for daily sitting), not by softness in the store aisle.",
        "Cut foam 1/4 in. oversize so the wrap compresses it slightly.",
        "Wrap batting snug, not stretched; staple to the underside, never the sides.",
        "One layer of batting over foam; two layers over bare plywood faces.",
      ],
      commonMistakes: ["Buying 'craft foam' because the price is nice - it is packaging foam and collapses in weeks", "Stretching batting until it compresses the foam edges square again, defeating its purpose"],
    },
    {
      id: "ml_pocket_holes_bench",
      title: "Pocket holes in 60 seconds",
      skillCategory: "Joinery",
      difficulty: "beginner",
      explanation:
        "An angled counterbore that lets a screw pull two panels together. For this bench: jig and bit collar both set to 3/4 in., coarse-thread 1-1/4 in. screws, pockets on the SIDE panels facing the storage interior.",
      steps: [
        "Set jig height and bit collar to 3/4 in.",
        "Three pockets per side-panel end, clamped while drilling.",
        "Clamp the joint flush while driving - pocket screws push panels out of line otherwise.",
      ],
      commonMistakes: ["Driving at full clutch and spinning the threads out of plywood - use a low clutch setting"],
    },
  ],
  mistakePrevention: [
    {
      mistake: "Buying pretty fashion fabric instead of upholstery-weight",
      whyItHappens: "The fashion aisle is bigger, cheaper, and full of gorgeous boucle-look bolts that are actually coat fabric.",
      howToAvoid: "Check the bolt-end label for 'upholstery' and a double-rub count (15,000+). If there is no rub count, it is not upholstery fabric.",
      howToFix: "If already bought: use it for the lid only (light wear) and buy proper goods for the body - or accept re-covering in a year.",
      affectedSteps: [10, 11, 12],
    },
    {
      mistake: "Stapling fabric directly over bare plywood edges",
      whyItHappens: "Batting seems optional when the fabric is thick.",
      howToAvoid: "Batting on every visible face and edge, no exceptions - it is $4 of material per face.",
      howToFix: "Pull the staples (they are free), add batting, re-wrap.",
      affectedSteps: [9, 12],
    },
    {
      mistake: "Hinge alignment discovered wrong after upholstery",
      whyItHappens: "Skipping the Step 5 dry fit to get to the fun fabric part sooner.",
      howToAvoid: "Pre-drill every hinge hole while the wood is bare; reinstall through fabric using an awl to find the holes.",
      howToFix: "Shift the hinge one screw-spacing over and re-drill through the fabric with firm awl pressure first (drilling unanchored through fabric wraps threads around the bit).",
      affectedSteps: [5, 13],
    },
    {
      mistake: "Foam cut ragged with a utility knife",
      whyItHappens: "A razor seems like the obvious foam tool; it drags and tears at 2 in. depth.",
      howToAvoid: "Serrated blade, long smooth full-depth strokes, zero downward pressure.",
      howToFix: "Hide scallops under an extra batting layer, or flip the ragged edge to the hinge side.",
      affectedSteps: [7],
    },
  ],
  commonProblems: [
    {
      problem: "Fabric wrinkles or scallops between staples",
      likelyCauses: ["Staples too far apart", "Pulling with fingertips instead of a flat palm drag", "Tension uneven between opposite sides"],
      fix: "Pull the staples in the wrinkled zone only, re-tension with a palm drag, staple every 2 in. Work centers-out, always opposite sides in pairs.",
      severity: "minor",
    },
    {
      problem: "Lid sits crooked or overhangs unevenly",
      likelyCauses: ["Hinge remounted off the pre-drilled holes", "Fabric bulk at the hinge edge"],
      fix: "Back the hinge screws out, find the original holes with an awl, trim fabric bulk to a single layer under the hinge leaf, remount.",
      severity: "minor",
    },
    {
      problem: "Lid slams shut",
      likelyCauses: ["Lid stay not installed", "Stay tension set too light for the upholstered lid weight"],
      fix: "Install/adjust the soft-close stay until the lid takes 3+ seconds to fall from fully open. With kids this is a safety stop, not a punch-list item.",
      severity: "safety_stop",
    },
    {
      problem: "Seat feels board-hard at the edges",
      likelyCauses: ["Fabric over-tensioned, compressing the foam edge", "Foam cut undersize"],
      fix: "Release the perimeter staples one side at a time and re-staple at snug-not-drum tension. If the foam was cut small, a wrap of extra batting recovers most of the loft.",
      severity: "minor",
    },
  ],
  safetyReview: {
    overallRisk: "low",
    summary:
      "A low-risk build: light power-tool work, staple gun, and adhesives. The one designed-in hazard to respect is the hinged lid around children - addressed with a required soft-close stay and ventilation holes. In service the bench is benign.",
    hazards: [
      { level: "medium", category: "Lid entrapment/pinch", issue: "A free-falling storage lid can injure small fingers; an airtight box is a hide-and-seek hazard.", mitigation: "Soft-close lid stay REQUIRED (spec'd in hardware); 1/4 in. ventilation holes drilled in Step 4; lid weight kept under 10 lb." },
      { level: "low", category: "Staple gun", issue: "A T50 gun drives a staple through a fingertip exactly once per lifetime of carelessness.", mitigation: "Both hands behind the gun's nose, never hold fabric within 2 in. of the staple line, treat it like the nail gun it almost is." },
      { level: "low", category: "Adhesive vapors", issue: "Spray adhesive is the strongest solvent exposure in the build.", mitigation: "Outdoors or wide-open door, no kids present, 30-minute airing before re-entry." },
      { level: "low", category: "Cutting", issue: "Circular saw or store cuts; serrated knife on foam.", mitigation: "Standard saw practice; cut foam on a stable surface, stroke away from the steadying hand." },
    ],
    ppe: ["Safety glasses for all cutting and stapling", "Dust mask for the sanding session", "Ventilation for spray adhesive and protector spray"],
    childPetNotes: [
      "The soft-close stay and ventilation holes exist specifically for the kids-in-the-house case - do not value-engineer them away.",
      "Choose a performance fabric if pets share the bench; claws and boucle loops are natural enemies.",
      "Protector spray and Danish oil both want 24-72 h of curing before kid contact.",
    ],
    structuralNotes: [
      "The box as drawn comfortably supports two seated adults (design target ~500 lb distributed) with conservative margins - as always, an estimate for a one-off build, not a certified rating.",
      "Standing on the lid concentrates load on the hinge line - house rule: sit, do not stand.",
      "Re-tighten the four legs after the first week; hanger bolts settle.",
    ],
    finishToxicityNotes: [
      "Danish oil rags must dry flat outdoors - self-heating in balled rags is a real fire mechanism.",
      "Fabric protector sprays: apply outdoors, cure 24 h; fully cured film is inert.",
    ],
    professionalReviewRecommended: false,
  },
  alternatives: [
    {
      id: "alt_fixed_top",
      name: "Fixed-Top Simple Bench",
      focus: "beginner",
      description: "Same box, same upholstery, no hinge or lid hardware - the top screws down permanently from inside.",
      estimatedCostLow: 250,
      estimatedCostHigh: 390,
      estimatedTime: "1 weekend",
      pros: ["Removes all lid-fit fussiness and the pinch hazard entirely", "3 hours faster"],
      cons: ["No storage access", "Loses half the reference's function"],
      keyChanges: ["No hinge/stay", "Top screwed from inside before body upholstery"],
    },
    {
      id: "alt_channel",
      name: "Channel-Look Upgrade",
      focus: "premium",
      description: "The Closest Match path: sewn channel-tufted lid cover with piping, premium performance boucle, zippered for cleaning.",
      estimatedCostLow: 450,
      estimatedCostHigh: 680,
      estimatedTime: "2-3 weekends",
      pros: ["The exact catalog look including stitch lines", "Removable, cleanable cover"],
      cons: ["Requires a sewing machine and intermediate confidence", "Roughly doubles cost"],
      keyChanges: ["Sewn cover replaces stapled wrap on the lid", "Piped edges", "Zipper closure"],
    },
    {
      id: "alt_smaller",
      name: "36-Inch Entryway Version",
      focus: "smaller",
      description: "The same design at 36 x 16 for tight entries; everything shrinks except foam thickness and hardware.",
      estimatedCostLow: 250,
      estimatedCostHigh: 400,
      estimatedTime: "1-2 weekends",
      pros: ["Fits narrow halls", "Fabric drops to 2 yd", "Lighter lid is gentler on the hinge"],
      cons: ["Seats one adult", "Less storage"],
      keyChanges: ["Box 36 x 16 x 12", "Lid 36 x 16", "Fabric 2 yd"],
    },
  ],
  builderHandoff: {
    projectSummary:
      "Commission an inspired-by upholstered storage bench: 48 x 18 x 19 in., fully upholstered plywood box with a hinged padded lid (2 in.+ high-density foam), soft-close lid stay, light boucle-type fabric, small tapered legs.",
    referenceStyle: "Boutique-modern upholstered bench (customer will supply reference photos). Inspired-by commission: match the proportions, thick padded lid profile, and nubby light fabric texture - an original piece in the same spirit.",
    desiredDimensions: "48 in. W x 18 in. D x ~19 in. seat height; interior storage ~44 x 15 x 10 in.; lid under 10 lb with soft-close hardware.",
    materials: ["Plywood carcass (no particleboard)", "HD36 or better seat foam", "Customer-approved upholstery fabric, 15,000+ double rubs", "Solid wood legs"],
    finish: "Fabric per approved swatch; legs in natural oil or matte black. Household includes children - fabric should be cleanable or protected.",
    constructionNotes: ["Soft-close lid stay required (child safety)", "Ventilation gaps or holes in the storage box", "Piano hinge preferred over paired butt hinges", "Dust cover on the underside"],
    budgetTarget: "$500-$800 including fabric (customer's DIY alternative is ~$300-470 in materials).",
    qualityExpectations: ["Drum-tight faces with no scallops", "Corner pleats uniform and directional", "Weave running true on every face", "Lid closes slowly and aligns with even reveals"],
    questionsForBuilder: [
      "Sewn fitted covers or stapled wrap at this budget?",
      "Can you channel-tuft the lid, and what does it add?",
      "What foam density do you use for daily-sit benches?",
      "Is COM (customer's own material) fabric acceptable, and how many yards do you need?",
    ],
    quoteRequestMessage:
      "Hi! I'd like a quote on a custom upholstered storage bench inspired by a boutique piece (photos attached): 48 x 18 x 19 in., hinged padded lid with soft-close stay, light boucle-type fabric, tapered wood legs. Kids in the house, so cleanable fabric and the soft-close hardware matter. Could you share ballpark pricing (with fabric vs COM), lead time, and whether you'd recommend a sewn or stapled cover at my budget of roughly $500-800? Thanks!",
  },
  finalChecklist: [
    "Lid falls slowly and silently from fully open - the stay is doing its job",
    "Press-test each corner: no wobble, no creak",
    "Weave runs parallel to edges on every face (sight down each panel)",
    "Corner pleats all face their assigned direction",
    "No staple visible anywhere without tipping the bench over",
    "Ventilation holes clear (not blocked by the fabric wrap)",
    "Legs snug + felt pads on",
    "Protector spray applied and cured 24 h before first sit",
  ],
  maintenance: [
    "Vacuum weekly-ish with the upholstery brush - grit ground into boucle is what wears it, not sitting.",
    "Blot spills immediately; clean whole panels, never spots, to avoid rings.",
    "Rotate decorative use: if one end gets all the sitting, the loops flatten unevenly - nudge household habits or rotate the bench.",
    "Re-apply fabric protector yearly (skip for built-in performance weaves).",
    "Re-tighten legs and check the lid stay tension at season changes.",
    "A battery fabric shaver handles normal pilling in 10 minutes.",
  ],
  qaNotes: [
    "Budget verified: five required categories sum to $297 low / $444 high; grand total high $470 = $444 + $26 contingency; savings computed from the $1,199 assumed reference price.",
    "Cut list fits one 4x8 sheet with 26 percent waste; fabric layout verified against 2.5 yd of 54 in. goods.",
    "Lid pinch hazard mitigated by required soft-close stay + ventilation holes; flagged requiredForSafety in the feasibility questions.",
    "Brand-safe: reference described generically as an inspired-by target; no reproduction claims.",
  ],
  confidenceScore: 78,
  createdAt: T,
  updatedAt: T,
};
