/**
 * Secondary category template: an inspired-by chunky woven wall hanging (the
 * oversized fiber-art pieces boutique decor shops sell for $250+). Used by the
 * mock pipeline for weaving / knitting / decor_craft projects, then adapted to
 * the user's constraints by generators.ts.
 *
 * A complete, valid BuildPlan with real fiber specs (8/4 cotton rug warp,
 * super-bulky #6/#7 wool-blend roving, rya knots) and arithmetic-consistent
 * budget lines.
 */
import type { BuildPlan } from "../../../shared/types";

const T = "2026-07-01T09:00:00.000Z";

export const wovenWallHangingTemplate: BuildPlan = {
  id: "tpl_woven_wall_hanging",
  projectId: "tpl_project",
  title: "Chunky Woven Wall Hanging - Balanced Build",
  snapshot: {
    inspiredBy: "Boutique oversized fiber-art wall hanging (user-provided reference)",
    projectType: "Woven item",
    selectedBuildPath: "balanced",
    difficulty: "Beginner",
    estimatedCostLow: 56,
    estimatedCostHigh: 101,
    estimatedTime: "2-3 evenings plus a loom-building hour (8-12 hours total)",
    visualMatchScore: 84,
    durabilityScore: 88,
    safetyRiskLabel: "Very low (hand tools only; light wall mounting)",
    bestFor: "A first weaving project - three techniques cover the whole boutique look, and the loom is four sticks and a box of nails",
    requiredWorkspace: "A couch and a coffee table. Genuinely.",
    mainMaterials: [
      "8/4 cotton rug warp (the skeleton)",
      "Wool-blend super bulky roving (the chunky texture)",
      "Bulky #5 accent yarn (contrast bands)",
      "1 in. hardwood dowel hanger",
    ],
    keyTools: ["Shop-made lap loom (1x2s + finish nails)", "Tapestry needle", "Dinner fork (the beater)", "Sharp scissors"],
  },
  worthItScore: {
    score: 88,
    verdict: "excellent",
    savingsPotential: 90,
    difficultyFit: 95,
    toolAccessibility: 98,
    materialAvailability: 85,
    visualMatchPotential: 86,
    safetyRisk: 98,
    timeCommitment: 85,
    explanation:
      "Fiber wall art has the widest retail markup in home decor: the $289 boutique piece is $50-90 of yarn plus hours of pleasant handwork. Unlike furniture dupes, there is no finish-matching risk and no structural risk - the worst case is unweaving an evening's work. The three techniques in this plan (tabby, soumak, rya) are the same three that produce 95 percent of the boutique looks, and the shop-made lap loom is a 30-minute build you keep forever. The one place beginners overspend is buying brand-name 'chunky wall hanging yarn' - wool-blend roving sold by the pound is the same material at half the price.",
    recommendation:
      "Absolutely build it. Make the loom, buy roving by weight not by branded skein, and expect your second hanging to start the week you finish this one - budget shelf space accordingly.",
  },
  savingsStory: {
    referencePrice: 289,
    referenceLabel: "Estimated retail (~$289 - typical boutique fiber-art pricing for this size; verify on the product page)",
    estimatedDiyCostLow: 56,
    estimatedDiyCostHigh: 101,
    estimatedSavings: 211,
    savingsPercentage: 73,
    toolCostsIncluded: true,
    laborTimeTradeoff:
      "About 8-12 relaxed evening hours for roughly $190-$230 in savings - and unlike most DIY, the labor here is the kind people do on purpose to unwind.",
    explanation:
      "The range covers the loom lumber and nails (a permanent tool you keep), a cone of cotton rug warp (enough for 3-4 future pieces), 1.5 lb of wool-blend roving, two accent skeins, the dowel, and hanging hardware. High end assumes full-price craft-store roving; the low end assumes buying roving by the pound online or with the perpetual 40 percent coupon.",
  },
  referenceAnalysis:
    "The reference is an oversized woven wall hanging whose impact comes from scale, fiber contrast, and a long dense fringe - not from technical complexity. Reading the photos: a plain tabby ground in a neutral wool, two or three raised horizontal braids (soumak stitch), cloud-thick sections of super bulky roving 'bubbled' in for loft, and a rya-knot fringe occupying the bottom third, trimmed to a shallow V. Every one of those elements is a beginner technique executed at generous scale. The wood at the top is a plain dowel or found branch. This is the single most faithful category of dupe: your version can be materially identical to the boutique piece, not just similar.",
  referenceAnalysisDetails: {
    shapeForm: "Rectangular weave, roughly 24 in. wide x 36 in. long including fringe, hung from a wooden dowel or branch; fringe trimmed straight or in a shallow V.",
    approxDimensions: "Estimated 24 in. wide weave, 18-20 in. of woven field, 14-16 in. of rya fringe - standard boutique proportions for the 'statement' size.",
    materials: "Cotton warp (hidden), cream/natural wool or wool-blend weft in several textures, super bulky roving for the cloud sections, wooden hanger.",
    finishColor: "Naturals: cream, oatmeal, undyed wool tones with occasional single accent band (rust, ochre, or dusty pink depending on colorway).",
    constructionStyle: "Frame-loom tapestry weaving: tabby ground, soumak braid accents, rya knot fringe, hemstitched or dowel-looped top edge.",
    decorativeDetails: "The texture contrast IS the design: flat tabby vs raised soumak braids vs airy roving bubbles vs dense fringe.",
    visible: [
      "Thick horizontal braid lines (soumak) between texture sections",
      "Cloud-loft sections of super bulky roving",
      "Dense rya fringe, deliberately trimmed",
      "Natural wood dowel with simple cord hang",
    ],
    uncertain: [
      "Exact fiber content (wool vs wool-blend vs acrylic - affects cost, not look)",
      "Warp spacing (we assume 4 ends per inch, standard for chunky work)",
      "Whether the reference is hand-woven or machine-assisted (irrelevant to the dupe)",
    ],
  },
  confidenceBreakdown: {
    overall: 86,
    referenceImage: 82,
    materials: 88,
    dimensions: 80,
    finish: 90,
    construction: 92,
    cost: 82,
    safety: 98,
    visualMatch: 86,
    uncertaintyNotes: [
      "Fiber content is the main unknown - the plan specs wool-blend roving, which matches the look of anything the boutique used.",
      "Fringe length drives yarn quantity more than any other variable; the shopping list includes a 20 percent fiber margin.",
    ],
    howToImproveConfidence: [
      "Measure the wall spot and confirm the 24 x 36 target reads right at viewing distance - wall hangings routinely disappoint by being too small.",
      "Order or swatch the roving before committing: 'super bulky' spans a 3x thickness range between brands.",
    ],
  },
  feasibilityQuestions: [
    {
      id: "q_size_wall",
      question: "How big is the wall space? The plan targets 24 in. wide x 36 in. long including fringe.",
      whyItMatters: "Scale is the number-one reason wall hangings disappoint - pieces that look huge on a couch vanish over one. Width sets the loom build and warp count; going to 30 in. wide changes both.",
      answerType: "text",
      requiredForSafety: false,
      assumptionIfSkipped: "We assume 24 in. wide x 36 in. long - the boutique 'statement' size that suits most walls over furniture.",
    },
    {
      id: "q_fiber",
      question: "Real wool / wool-blend roving, or budget acrylic?",
      whyItMatters: "Wool-blend roving has the matte loft of the boutique references and blooms when steamed; acrylic is 40 percent cheaper, slightly shinier, and a touch springier. Both photograph well.",
      answerType: "single_choice",
      options: ["Wool-blend (closest match)", "Acrylic (budget)", "Mix: wool where it shows most"],
      requiredForSafety: false,
      assumptionIfSkipped: "We assume wool-blend roving for the texture sections and let the accent bands be anything with the right color.",
    },
    {
      id: "q_colorway",
      question: "All-neutral (cream/oatmeal), or with an accent color band?",
      whyItMatters: "It only changes one skein on the shopping list, but accent placement is planned in the layout step - easier decided now than unwoven later.",
      answerType: "single_choice",
      options: ["All neutrals", "Rust accent", "Ochre accent", "Dusty pink accent", "Other (tell us)"],
      requiredForSafety: false,
      assumptionIfSkipped: "We assume all neutrals - the most common reference colorway and impossible to get wrong.",
    },
  ],
  assumptions: [
    "Reference retail assumed ~$289; boutique fiber pieces this size run $200-450 depending on the shop.",
    "Finished size 24 in. wide x ~36 in. long including 14-16 in. of fringe; woven field about 18-20 in.",
    "Warp spacing 4 ends per inch (97 warp ends at 24 in. plus selvedge doubling) - the standard for super bulky weft.",
    "Fiber quantities: ~1.5 lb roving + 2 accent skeins covers the plan with about 20 percent margin.",
    "The lap loom is built from two 8 ft 1x2 furring strips - $10 of lumber that becomes permanent equipment.",
  ],
  buildPaths: [
    {
      id: "path_mvd",
      name: "minimum_viable_dupe",
      label: "Minimum Viable Dupe",
      estimatedCostLow: 30,
      estimatedCostHigh: 55,
      estimatedTime: "1 evening + loom hour",
      difficulty: "Absolute beginner",
      visualMatchScore: 60,
      durabilityScore: 85,
      requiredTools: ["Lap loom", "Fork", "Scissors"],
      pros: ["One technique only (tabby + fringe)", "All-acrylic budget fiber", "Done in one committed evening"],
      cons: ["No soumak braids or roving clouds - flatter texture", "Acrylic sheen reads slightly craft-fair up close"],
      bestFor: "Testing the size on your wall and the hobby on yourself",
      compromises: ["Single texture", "Acrylic fiber", "Straight-cut fringe"],
    },
    {
      id: "path_balanced",
      name: "balanced",
      label: "Balanced Build",
      estimatedCostLow: 56,
      estimatedCostHigh: 101,
      estimatedTime: "2-3 evenings (8-12 hours)",
      difficulty: "Beginner",
      visualMatchScore: 84,
      durabilityScore: 88,
      requiredTools: ["Lap loom", "Tapestry needle", "Fork beater", "Scissors"],
      pros: ["All three boutique techniques (tabby, soumak, rya)", "Wool-blend roving where texture shows", "The loom is reusable equipment, not consumable"],
      cons: ["Wool-blend costs real money by the pound", "Rya fringe consumes fiber deceptively fast"],
      bestFor: "The full reference look on the first try - what this plan's steps describe",
      compromises: ["Dowel instead of found driftwood (upgrade free by walking a beach)"],
      recommendationReason: "Every visible element of the reference at half the retail price, with techniques sized to a first-timer.",
      recommended: true,
    },
    {
      id: "path_closest",
      name: "closest_match",
      label: "Closest Match",
      estimatedCostLow: 95,
      estimatedCostHigh: 160,
      estimatedTime: "4-5 evenings (16-20 hours)",
      difficulty: "Advanced beginner",
      visualMatchScore: 93,
      durabilityScore: 90,
      requiredTools: ["Everything in Balanced", "Shed stick + heddle bar (add to the loom)", "Steamer or iron"],
      pros: ["100 percent wool everywhere including hand-dyed accent", "Added twill and double-soumak passages for richer texture", "Steam-blocked and weighted finish - gallery-flat"],
      cons: ["Hand-dyed skeins are $18-28 each", "Doubles the hours"],
      bestFor: "Someone who already knows they love fiber work",
      compromises: ["None visible - the compromise is money and evenings"],
    },
  ],
  recommendedPathReason:
    "Balanced hits the entire visible technique list of the reference - tabby ground, soumak braids, roving clouds, rya fringe - using fiber bought by weight instead of by branded skein. The Minimum Viable path exists to test scale; the Closest Match path upgrades fiber and density, not appearance category.",
  designSimplifier: {
    difficultOriginalDetails: [
      { detail: "Perfectly even selvedges (side edges)", whyDifficult: "Edge tension is the one genuine skill in tapestry weaving; pros make it look automatic. Beginners pull edges into an hourglass." },
      { detail: "Complex multi-shuttle color blending", whyDifficult: "Some boutique pieces blend 4-5 weft colors mid-row - fiddly shuttle management." },
      { detail: "Found-driftwood hanger with invisible mounting", whyDifficult: "Drilling irregular driftwood without splitting takes patience and luck." },
    ],
    simplifications: [
      { original: "Free-hand even selvedges", simplified: "Doubled selvedge warps + the bubbling technique in every weft row", fidelityImpact: "Nearly eliminates edge pull-in; the doubled edge reads as a deliberate border." },
      { original: "Multi-color blended passages", simplified: "Distinct horizontal bands separated by soumak braids", fidelityImpact: "Matches the most popular reference style anyway - banded, not blended." },
      { original: "Driftwood hanger", simplified: "1 in. hardwood dowel (swap for driftwood any time - the top loops fit either)", fidelityImpact: "Slightly more 'finished' look; zero structural difference." },
    ],
    preservedElements: ["24 in. statement width", "All three signature textures", "Dense trimmed rya fringe", "Natural fiber palette"],
    changedElements: ["Banded layout instead of blended", "Dowel hanger by default"],
    removedElements: ["Twill passages (Closest Match path adds them back)"],
    fidelityLossSummary: "At viewing distance the piece reads identical to the reference category; up close a weaver would notice simpler passages and admire your selvedges.",
    rationale: "Every simplification converts a practice-dependent skill into a structure-dependent one - structure is buildable on day one, practice is not.",
  },
  minimumViableDupe: {
    summary: "One evening, one technique: a tabby-woven field in cream acrylic with a long straight fringe on the same shop-made loom.",
    mustPreserveElements: ["24 in. width (scale is the design)", "Dense fringe at least 12 in. long", "Neutral palette"],
    canSimplifyElements: ["Single tabby texture", "Straight-cut fringe", "Acrylic fiber"],
    canRemoveElements: ["Soumak braids", "Roving cloud sections", "Accent bands"],
    constructionApproach: "Warp the loom at 4 ends per inch, weave 14 in. of tabby with doubled strands, rya-knot the fringe, hang from the dowel.",
    estimatedCostLow: 30,
    estimatedCostHigh: 55,
    estimatedTime: "1 evening plus the loom hour",
    fidelityTradeoff: "Roughly 70 percent of the look; 100 percent of the scale test. The loom and warp cone carry forward to the full version.",
  },
  dimensions: [
    { label: "Loom (outer frame)", value: "28 x 36 in.", source: "standard", confidence: 95 },
    { label: "Woven width", value: "24 in.", source: "estimated", confidence: 80 },
    { label: "Woven field length", value: "18-20 in.", source: "estimated", confidence: 75 },
    { label: "Rya fringe length", value: "14-16 in. before trimming", source: "estimated", confidence: 80 },
    { label: "Overall hung length", value: "~36 in. incl. fringe", source: "estimated", confidence: 75 },
    { label: "Warp spacing", value: "4 ends per inch", source: "standard", confidence: 90 },
    { label: "Dowel", value: "1 in. dia. x 30 in.", source: "standard", confidence: 90 },
  ],
  materials: [
    {
      name: "Cotton rug warp",
      category: "Fiber",
      quantity: "1 cone (800 yd)",
      specification: "8/4 cotton carpet warp, natural - the standard tapestry warp; strong enough to tension hard",
      purpose: "The hidden skeleton every weft rides on; a cone does 3-4 hangings",
      estimatedCostLow: 10,
      estimatedCostHigh: 14,
      budgetAlternative: "Cotton butcher's twine in a pinch (fuzzier, weaker - acceptable once)",
      notes: "Do NOT warp with knitting yarn - it stretches under tension and the whole weave goes wavy when it relaxes.",
    },
    {
      name: "Wool-blend roving",
      category: "Fiber",
      quantity: "~1.5 lb",
      specification: "Super bulky (#6-7) wool or wool-blend roving/pencil roving, cream + oatmeal - sold by the pound online or in bump/bun put-ups",
      purpose: "The cloud-loft sections and most of the rya fringe - the signature texture",
      estimatedCostLow: 16,
      estimatedCostHigh: 30,
      budgetAlternative: "Acrylic 'jumbo' yarn (Bernat Blanket-class) at roughly 60% the cost, slightly shinier",
      premiumAlternative: "100% merino roving - the cloud sections bloom beautifully when steamed (+$15-25)",
      notes: "Buy by weight, not by branded 'wall hanging kit' skein - kits charge double per ounce for the same fiber.",
    },
    {
      name: "Accent yarn",
      category: "Fiber",
      quantity: "2 skeins",
      specification: "Bulky (#5) wool-blend, one neutral (oatmeal/gray) + one accent color if chosen",
      purpose: "Tabby ground bands and the soumak braids - needs more twist than roving to show the braid structure",
      estimatedCostLow: 8,
      estimatedCostHigh: 14,
      notes: "Soumak braids read best in a yarn with visible twist; roving braids blur together.",
    },
    {
      name: "Furring strips, 1x2",
      category: "Loom lumber",
      quantity: "2 @ 8 ft",
      specification: "1 in. x 2 in. x 8 ft pine furring, sighted straight",
      purpose: "The lap loom frame: two 36 in. rails, two 28 in. rails, plus corner braces from the offcuts",
      estimatedCostLow: 6,
      estimatedCostHigh: 9,
    },
    {
      name: "Finish nails",
      category: "Loom hardware",
      quantity: "1 box",
      specification: "1-1/4 in. (3d) finish nails - about 120 used as warp pegs",
      purpose: "Two rows of warp pegs at 1/2 in. spacing (doubled to 4 ends/in. by winding)",
      estimatedCostLow: 4,
      estimatedCostHigh: 6,
    },
    {
      name: "Hardwood dowel",
      category: "Hanger",
      quantity: "1",
      specification: "1 in. diameter x 36 in. poplar or oak dowel, cut to 30 in.",
      purpose: "The hanger the finished weave transfers onto",
      estimatedCostLow: 6,
      estimatedCostHigh: 9,
      premiumAlternative: "Found driftwood or a pruned branch, bark eased off - free and more boutique",
    },
    {
      name: "Tapestry needle + comb",
      category: "Notions",
      quantity: "1 set",
      specification: "Large-eye blunt tapestry needles (2-3 sizes) - a wide-tooth comb or dinner fork is the beater",
      purpose: "Needle-weaving the weft; packing rows down evenly",
      estimatedCostLow: 3,
      estimatedCostHigh: 5,
    },
    {
      name: "Hanging hardware",
      category: "Notions",
      quantity: "1 set",
      specification: "Cotton cord or leather lace for the dowel + two small cup hooks or a picture hook rated 10 lb",
      purpose: "Getting it on the wall; the finished piece weighs about 2 lb",
      estimatedCostLow: 3,
      estimatedCostHigh: 6,
    },
  ],
  materialSwaps: [
    {
      originalMaterial: "Wool-blend roving",
      alternativeMaterial: "Acrylic jumbo yarn (blanket-class)",
      costImpact: "lower",
      durabilityImpact: "similar",
      visualMatchImpact: "lower",
      difficultyImpact: "similar",
      pros: ["40 percent cheaper", "Machine-washable if it ever needs it", "Moth-proof"],
      cons: ["Slight sheen under direct light", "Does not bloom when steamed - the clouds stay tidier, less organic"],
      notes: "The right call for humid climates, moth anxiety, or a strict budget. Mix approach: acrylic in the tabby ground, wool where the loft shows.",
    },
    {
      originalMaterial: "8/4 cotton rug warp",
      alternativeMaterial: "Nylon mason line",
      costImpact: "similar",
      durabilityImpact: "higher",
      visualMatchImpact: "similar",
      difficultyImpact: "harder",
      pros: ["Nearly unbreakable under tension"],
      cons: ["Slippery - knots need to be doubled", "Slight stretch memory can wave the weave"],
      notes: "Only if the hardware store trip already happened and the craft store is far. Cotton warp is worth the errand.",
    },
    {
      originalMaterial: "Hardwood dowel hanger",
      alternativeMaterial: "Copper pipe (1/2 in. type M)",
      costImpact: "similar",
      durabilityImpact: "similar",
      visualMatchImpact: "similar",
      difficultyImpact: "similar",
      pros: ["A deliberate modern-metallic look some references use", "Dead straight forever"],
      cons: ["Reads industrial rather than organic", "Cold color against warm naturals"],
      notes: "Style call, not a quality call.",
    },
  ],
  hardware: [
    {
      name: "Wood glue",
      category: "Loom build",
      quantity: "1 small bottle",
      specification: "4-8 oz PVA",
      purpose: "Loom corner joints (with screws)",
      estimatedCostLow: 4,
      estimatedCostHigh: 6,
      notes: "Costed inside the loom lumber line if you already own any glue at all.",
    },
    {
      name: "Wood screws",
      category: "Loom build",
      quantity: "8",
      specification: "#8 x 1-1/4 in.",
      purpose: "Loom corners - one per corner face plus braces",
      estimatedCostLow: 2,
      estimatedCostHigh: 3,
      notes: "From the junk drawer; counted in the loom line.",
    },
  ],
  tools: [
    { name: "Lap loom (shop-made, Step 1)", required: true, category: "Weaving", purpose: "Holds the warp under tension - the entire workshop for this craft", owned: false, estimatedCostIfBuying: "$10-15 to build vs $60-120 to buy this size", beginnerNote: "Building it IS Step 1 of the plan." },
    { name: "Drill/driver", required: true, category: "Power tool", purpose: "Loom corner screws; pilot holes so 1x2 pine does not split", owned: true },
    { name: "Hammer", required: true, category: "Hand tool", purpose: "Setting ~120 finish-nail warp pegs", owned: true },
    { name: "Tapestry needle", required: true, category: "Weaving", purpose: "Carrying weft through the shed for fine rows", owned: false, estimatedCostIfBuying: "$3-5" },
    { name: "Dinner fork or wide-tooth comb", required: true, category: "Weaving", purpose: "The beater - packing each row down evenly", owned: true, beginnerNote: "A fork genuinely outperforms cheap 'weaving combs.' Free is also nice." },
    { name: "Sharp scissors", required: true, category: "Cutting", purpose: "Fringe trimming - sharpness matters for the final cut", owned: true, beginnerNote: "The final fringe trim wants the sharpest scissors in the house; dull blades chew roving." },
    { name: "Ruler / yardstick", required: true, category: "Layout", purpose: "Warp spacing, fringe trim line", owned: true },
    { name: "Shed stick (paint stirrer)", required: false, category: "Weaving", purpose: "Holds alternate warps open so tabby rows fly instead of crawl", owned: false, substitute: "A free paint stirrer or a ruler - flip it on edge to open the shed", estimatedCostIfBuying: "$0 (paint counter)" },
    { name: "Garment steamer or iron", required: false, category: "Finishing", purpose: "Blooming the wool and relaxing the finished weave flat", owned: false, substitute: "A bathroom steamed by a hot shower does 80 percent of the job" },
  ],
  toolAwareNotes: [
    {
      missingTool: "Loom",
      impact: "No loom, no weaving",
      workaround: "Step 1 builds one from $10 of furring strips in about an hour. It outlives store-bought frame looms and is exactly the size this plan needs.",
      workaroundType: "technique_change",
    },
    {
      missingTool: "Weaving comb / beater",
      impact: "Rows need packing down evenly after every pass",
      workaround: "A dinner fork. This is not a compromise - many production weavers prefer forks for chunky work.",
      workaroundType: "substitute_tool",
    },
  ],
  buildReadiness: {
    score: 92,
    readyStatus: "ready",
    missingTools: ["The loom itself (built in Step 1)", "Tapestry needles ($3-5)"],
    missingMaterials: ["Everything on the (short) shopping list"],
    skillGaps: ["None that matter - all three techniques are learned on the piece itself; the first two inches of tabby are the practice"],
    workspaceConcerns: ["None. This is couch craft. Keep roving away from velcro and enthusiastic cats."],
    budgetConcerns: ["Roving by the pound online vs branded skeins in-store is a 2x price difference for identical fiber"],
    safetyConcerns: ["None beyond a hammer and scissors"],
    recommendation: "Build the loom tonight, warp it tomorrow, weave the weekend. There is no readiness gap on this one - it is the lowest-barrier project in the library.",
  },
  difficultyBreakdown: {
    overall: "beginner",
    cuttingAccuracy: "Minimal: four lumber cuts within 1/8 in.; fringe trimming is the only precision moment",
    assembly: "Trivial: one glued-and-screwed rectangle",
    joinery: "None beyond the loom corners",
    finishMatching: "None - fiber color is chosen, not mixed",
    toolComplexity: "Hand tools only",
    physicalHandling: "A 2 lb finished piece; nothing heavy anywhere",
    safetyRisk: "Very low",
    timeCommitment: "8-12 pleasant hours; pauses cost nothing (tension holds between sessions)",
    repairability: "Excellent: any row can be unwoven and redone at any point before removal from the loom",
    beginnerTolerance: "The highest of any project category - mistakes unweave",
    notes: ["The only 'skill wall' is selvedge tension, and the doubled-edge-warp trick in Step 2 walls it off."],
  },
  cutList: [
    { partName: "Loom side rail", quantity: 2, material: "1x2 pine furring", dimensions: "36 in." },
    { partName: "Loom end rail (peg rails)", quantity: 2, material: "1x2 pine furring", dimensions: "28 in.", notes: "The nail pegs go in these." },
    { partName: "Corner brace", quantity: 4, material: "1x2 offcut", dimensions: "6 in., ends cut at 45 degrees", notes: "Optional but kills frame racking under warp tension." },
    { partName: "Hanger dowel", quantity: 1, material: "1 in. hardwood dowel", dimensions: "30 in." },
    { partName: "Warp ends", quantity: 100, material: "8/4 cotton warp", dimensions: "~48 in. each (wound continuously)", notes: "97 working ends at 4/in. across 24 in. + doubled selvedges." },
    { partName: "Rya fringe bundles", quantity: 48, material: "Roving + accent yarn", dimensions: "Cut 32-36 in., folded to 16-18 in.", notes: "3-4 strands per knot, 2 knots per inch across 24 in." },
  ],
  cutOptimizationPlans: [
    {
      material: "1x2 pine furring strip",
      sourceSize: "8 ft x 2 pieces",
      cuts: [
        { partName: "Side rails", quantity: 2, dimensions: "36 in.", precision: "rough", notes: "Both from strip 1." },
        { partName: "End rails", quantity: 2, dimensions: "28 in.", precision: "rough", notes: "Both from strip 2." },
        { partName: "Corner braces", quantity: 4, dimensions: "6 in. with 45-degree ends", precision: "rough", notes: "From the strip 1 remainder." },
      ],
      estimatedWastePercent: 15,
      sequenceNotes: [
        "Cut both 36 in. rails first from one strip, both 28 in. rails from the other - each pair from the same strip stays the same actual width.",
        "Any saw works: hand saw, circular saw, or the store's chop saw.",
      ],
    },
  ],
  storeCutSheet: undefined,
  budgetBreakdown: {
    lines: [
      {
        category: "Loom & hanger",
        items: [
          { name: "1x2 furring strips (2 @ 8 ft)", costLow: 6, costHigh: 9 },
          { name: "Finish nails 1-1/4 in. (box)", costLow: 4, costHigh: 6 },
          { name: "Hardwood dowel 1 in. x 36", costLow: 6, costHigh: 9 },
        ],
        subtotalLow: 16,
        subtotalHigh: 24,
      },
      {
        category: "Fiber",
        items: [
          { name: "8/4 cotton rug warp cone", costLow: 10, costHigh: 14 },
          { name: "Wool-blend roving ~1.5 lb", costLow: 16, costHigh: 30 },
          { name: "Accent yarn, bulky (2 skeins)", costLow: 8, costHigh: 14 },
        ],
        subtotalLow: 34,
        subtotalHigh: 58,
      },
      {
        category: "Notions & hanging",
        items: [
          { name: "Tapestry needles", costLow: 3, costHigh: 5 },
          { name: "Cord + wall hook (10 lb rated)", costLow: 3, costHigh: 6 },
        ],
        subtotalLow: 6,
        subtotalHigh: 11,
      },
      {
        category: "Contingency",
        items: [{ name: "Extra fringe fiber buffer", costLow: 0, costHigh: 8, optional: true }],
        subtotalLow: 0,
        subtotalHigh: 8,
      },
    ],
    materialsTotalLow: 56,
    materialsTotalHigh: 93,
    optionalToolsLow: 0,
    optionalToolsHigh: 0,
    grandTotalLow: 56,
    grandTotalHigh: 101,
    referencePrice: 289,
    estimatedSavingsLow: 188,
    estimatedSavingsHigh: 233,
    confidence: 82,
    notes: [
      "Required categories sum to $56 low / $93 high; grand total high $101 = $93 + $8 fringe buffer.",
      "The loom line is equipment, not consumable - your second hanging costs fiber only (roughly $35-60).",
      "Roving price assumes by-the-pound online purchase at the low end, full-price craft store at the high end.",
    ],
  },
  shoppingListByDepartment: [
    {
      store: "Home Depot",
      department: "Lumber & Hardware",
      items: [
        { name: "1x2 furring strips", quantity: "2 @ 8 ft", spec: "pine, sighted straight", estimatedCostLow: 6, estimatedCostHigh: 9, required: true },
        { name: "Finish nails", quantity: "1 box", spec: "1-1/4 in. (3d)", estimatedCostLow: 4, estimatedCostHigh: 6, required: true },
        { name: "Hardwood dowel", quantity: "1", spec: "1 in. x 36 in. poplar or oak", estimatedCostLow: 6, estimatedCostHigh: 9, required: true },
        { name: "Picture hook", quantity: "1", spec: "10 lb rated", estimatedCostLow: 2, estimatedCostHigh: 4, required: true },
      ],
    },
    {
      store: "Joann",
      department: "Yarn & Fiber",
      items: [
        { name: "Cotton rug warp", quantity: "1 cone", spec: "8/4 cotton carpet warp, natural, 800 yd", estimatedCostLow: 10, estimatedCostHigh: 14, required: true, notes: "Sometimes shelved with macrame cord - same aisle neighborhood." },
        { name: "Wool-blend roving", quantity: "~1.5 lb", spec: "super bulky #6-7, cream + oatmeal", estimatedCostLow: 16, estimatedCostHigh: 30, required: true, notes: "Cheaper by the pound online (wool bumps/buns) if you can wait for shipping." },
        { name: "Bulky accent yarn", quantity: "2 skeins", spec: "#5 bulky, visible twist, neutral + accent", estimatedCostLow: 8, estimatedCostHigh: 14, required: true },
        { name: "Tapestry needles", quantity: "1 pack", spec: "large-eye blunt, assorted", estimatedCostLow: 3, estimatedCostHigh: 5, required: true },
        { name: "Cotton cord / leather lace", quantity: "1 yd", spec: "for the dowel hang", estimatedCostLow: 1, estimatedCostHigh: 2, required: true },
      ],
    },
  ],
  projectTimeline: [
    {
      phase: "Loom build & warping",
      dayOrSession: "Evening 1 (or a Saturday hour + evening)",
      estimatedDuration: "2-3 hours",
      tasks: ["Cut and assemble the lap loom (Step 1)", "Set the nail pegs (Step 2)", "Wind the warp (Step 3)", "Weave the header (Step 4)"],
    },
    {
      phase: "The woven field",
      dayOrSession: "Evening 2 (+ spillover)",
      estimatedDuration: "3-5 hours",
      tasks: ["Tabby ground bands (Step 5)", "First soumak braid (Step 6)", "Roving cloud sections (Step 7)", "Remaining bands and braids (Step 8)"],
      notes: "Stop anywhere - warp tension holds for weeks between sessions.",
    },
    {
      phase: "Fringe & finishing",
      dayOrSession: "Evening 3",
      estimatedDuration: "3-4 hours",
      tasks: ["Rya fringe rows (Step 9)", "Hemstitch the top edge (Step 10)", "Release from loom, transfer to dowel (Step 11)", "Weave in ends (Step 12)", "Steam, trim the fringe, hang (Steps 13-14)"],
      waitTime: "Optional overnight hang before the final fringe trim - fiber relaxes and drops slightly.",
    },
  ],
  preBuildChecklist: [
    "Tape the 24 x 36 in. outline on the wall and live with it a day - confirm the scale before buying fiber.",
    "Verify roving thickness in hand or via a photographed coin-for-scale listing shot - 'super bulky' spans brands wildly.",
    "Sight down the furring strips at the store; a bowed rail makes a bowed warp.",
    "Wind all fringe bundles BEFORE starting the rya rows - cutting 48 bundles mid-flow kills the rhythm.",
    "Sharpest scissors in the house located and reserved for the final trim.",
  ],
  steps: [
    {
      stepNumber: 1,
      title: "Build the lap loom",
      estimatedTime: "1 hour",
      goal: "A rigid 28 x 36 in. frame that can hold 100 warps under real tension",
      toolsNeeded: ["Saw (any)", "Drill/driver", "Square"],
      materialsNeeded: ["1x2 rails", "Corner braces", "Wood glue", "#8 x 1-1/4 screws"],
      instructions: [
        "Cut rails per the cut list: two at 36 in., two at 28 in., four 6 in. braces with 45-degree ends.",
        "Assemble the rectangle with the 28 in. rails ON TOP of the 36 in. rails' ends (end rails must present a flat face for the nail pegs).",
        "Pilot-drill everything - 1x2 pine splits if you look at it wrong - then glue and screw each corner.",
        "Glue and screw a brace across each corner's inside angle.",
      ],
      qualityCheck: "Frame diagonals match within 1/4 in.; no flex when you try to rack it by hand.",
      commonMistake: "Skipping pilot holes and splitting a rail at the last screw.",
      phase: "Loom",
    },
    {
      stepNumber: 2,
      title: "Set the warp pegs",
      estimatedTime: "45 minutes",
      goal: "Two matching rows of finish-nail pegs at 1/2 in. spacing",
      toolsNeeded: ["Hammer", "Ruler", "Pencil"],
      materialsNeeded: ["Finish nails"],
      instructions: [
        "On each 28 in. end rail, mark a line down the center, then tick every 1/2 in. across the middle 25 in. (51 marks per rail).",
        "Drive a finish nail at each tick, leaning about 10 degrees AWAY from the weaving area, 1/2 in. deep - the lean keeps tensioned warp from popping off.",
        "Match the two rails mark-for-mark; a warp that runs diagonally telegraphs through the whole weave.",
      ],
      qualityCheck: "Sight across both peg rows - even spacing, consistent lean, no wobblers.",
      commonMistake: "Driving pegs dead vertical; the first hard tension pull then lifts warps off the pegs.",
      phase: "Loom",
    },
    {
      stepNumber: 3,
      title: "Wind the warp",
      estimatedTime: "45 minutes",
      goal: "97 working ends at even, guitar-string-adjacent tension, with doubled selvedges",
      toolsNeeded: ["The loom"],
      materialsNeeded: ["Cotton rug warp cone"],
      instructions: [
        "Tie onto the first peg with a double knot, then wind down-around-up-around continuously: down to the bottom rail's matching peg, around it, back up to the next top peg.",
        "Keep tension firm and CONSISTENT - it should twang softly when plucked. Consistency beats tightness.",
        "Double-wrap the first two and last two pegs - doubled selvedge warps are the edge-straightness insurance.",
        "Tie off the final end with a double knot and a dab of glue if it feels doubtful.",
      ],
      qualityCheck: "Every warp twangs at roughly the same pitch; no warp crosses its neighbor.",
      commonMistake: "Tension drifting looser across the width - re-tension by taking up slack peg-by-peg toward the tie-off end.",
      relatedMiniLessons: ["ml_warp_tension"],
      phase: "Warping",
    },
    {
      stepNumber: 4,
      title: "Weave the header",
      estimatedTime: "20 minutes",
      goal: "A 1/2 in. band of scrap-yarn tabby that spaces the warps evenly - removed at the end",
      toolsNeeded: ["Tapestry needle", "Fork"],
      materialsNeeded: ["Scrap yarn (any)"],
      instructions: [
        "Starting 2 in. up from the bottom pegs, needle-weave 4-5 rows of over-under tabby with scrap yarn.",
        "Beat each row down gently with the fork until the warps sit evenly spaced at 4 per inch.",
        "This header holds spacing for the rya fringe row that comes next; it pulls out during finishing.",
      ],
      qualityCheck: "Warp spacing even across the full 24 in.; no pairs bunched together.",
      phase: "Weaving",
    },
    {
      stepNumber: 5,
      title: "First rya fringe row",
      estimatedTime: "1.5 hours",
      goal: "The bottom fringe - 48 rya knots of roving that will become the piece's biggest visual mass",
      toolsNeeded: ["Scissors", "Ruler"],
      materialsNeeded: ["Roving + accent yarn fringe bundles (pre-cut 32-36 in.)"],
      instructions: [
        "Make each rya knot over a PAIR of warps: lay the folded bundle across two warps, wrap the tails around the outside of each warp, pull both tails down through the middle, snug the knot downward.",
        "Work 2 knots per inch across the width, alternating roving-heavy and yarn-mixed bundles for natural texture.",
        "Push each knot firmly down against the header; the knots' bulk is what hides the header line.",
        "Do not trim anything yet - the trim is the final step of the whole project.",
      ],
      qualityCheck: "Knot row sits level; bundles hang with roughly even density (thin spots get a second knot).",
      relatedMiniLessons: ["ml_rya_knot"],
      phase: "Weaving",
    },
    {
      stepNumber: 6,
      title: "Tabby ground band",
      estimatedTime: "1 hour",
      goal: "3 in. of clean over-under weaving above the fringe - the foundation texture",
      toolsNeeded: ["Tapestry needle or shed stick", "Fork"],
      materialsNeeded: ["Bulky accent yarn (neutral)"],
      instructions: [
        "Weave over-under across, then under-over back. Use the shed stick flipped on edge to open every other row and the pace doubles.",
        "BUBBLE every row: lay the weft in a series of arcs (like a row of small hills) before beating it down. Bubbling feeds extra length so edges do not pull in.",
        "Beat each row snug but not crushed - tabby should look like brickwork, not a solid wall.",
        "Check the width against a 24 in. mark every 10 rows; if it is narrowing, bubble more generously.",
      ],
      qualityCheck: "Selvedges vertical; width still 24 in.; rows level.",
      commonMistake: "Pulling the weft straight across without bubbling - the classic hourglass waist appears within 2 in.",
      relatedMiniLessons: ["ml_tabby_bubbling"],
      phase: "Weaving",
    },
    {
      stepNumber: 7,
      title: "First soumak braid",
      estimatedTime: "30 minutes",
      goal: "A raised braided line that separates texture sections - the signature boutique detail",
      toolsNeeded: ["Fingers (really)"],
      materialsNeeded: ["Bulky accent yarn, doubled"],
      instructions: [
        "Soumak: working left to right, wrap the doubled yarn OVER 4 warps forward, then back UNDER 2, over 4, under 2, all the way across.",
        "Work a second pass right to left with the same wrap - the two passes lean opposite ways and read as a braid.",
        "Beat down gently; soumak should sit proud of the tabby, not sink into it.",
      ],
      qualityCheck: "The braid reads as a continuous rope across the full width, no skipped wraps.",
      relatedMiniLessons: ["ml_soumak"],
      phase: "Weaving",
    },
    {
      stepNumber: 8,
      title: "Roving cloud section",
      estimatedTime: "45 minutes",
      goal: "2-3 in. of super-bulky loft - the texture people reach out to touch",
      toolsNeeded: ["Fingers", "Fork"],
      materialsNeeded: ["Wool-blend roving"],
      instructions: [
        "Weave the roving in plain tabby but over-under PAIRS of warps (over 2, under 2) - full-width roving crushed at 1/1 loses its loft.",
        "Bubble hugely - roving has zero stretch to give back and pulls edges hard.",
        "Beat only with fingers, pressing gently; a fork tears roving apart.",
        "Two to three passes fill the section; do not force more in than fits fluffy.",
      ],
      qualityCheck: "The section looks over-stuffed and cloud-like; edges still at 24 in.",
      commonMistake: "Beating roving down like yarn - it compacts into sad felt-rope and the loft never recovers.",
      phase: "Weaving",
    },
    {
      stepNumber: 9,
      title: "Build out the composition",
      estimatedTime: "2-3 hours",
      goal: "Alternate bands to fill the field: tabby, soumak, cloud, accent band, to ~18 in. total woven height",
      toolsNeeded: ["Everything so far"],
      materialsNeeded: ["All fibers"],
      instructions: [
        "Classic boutique layout from bottom: fringe -> 3 in. tabby -> soumak -> 2.5 in. cloud -> soumak -> 2 in. tabby (accent color here if chosen) -> cloud -> soumak -> tabby to the top.",
        "Step back across the room every band - weavings are composed at viewing distance, not at nose distance.",
        "Keep a photo of the reference beside the loom and match proportions, not exact rows.",
        "Change any band you dislike NOW by unweaving it - a five-minute undo that becomes impossible after removal.",
      ],
      qualityCheck: "Woven field measures ~18 in.; composition reads balanced from 8 ft away.",
      phase: "Weaving",
    },
    {
      stepNumber: 10,
      title: "Hemstitch the top edge",
      estimatedTime: "30 minutes",
      goal: "A locked top edge that cannot unravel when tension releases",
      toolsNeeded: ["Tapestry needle"],
      materialsNeeded: ["Matching yarn, ~2 yd"],
      instructions: [
        "With a threaded needle, hemstitch across the top: wrap each group of 2 warps together with a pass through the last rows of weft, snugging each wrap.",
        "Keep wraps consistent - this row shows just under the dowel.",
        "Tie off both ends with doubled half-hitches and thread the tails back into the weave.",
      ],
      qualityCheck: "Tug a top weft row sideways - nothing shifts.",
      commonMistake: "Skipping hemstitch because the weave 'feels tight' on the loom. Off-loom, unlocked wefts migrate within weeks.",
      phase: "Finishing",
    },
    {
      stepNumber: 11,
      title: "Release and transfer to the dowel",
      estimatedTime: "45 minutes",
      goal: "The weave off the loom and hanging from its dowel with even warp loops",
      toolsNeeded: ["Scissors"],
      materialsNeeded: ["Dowel"],
      instructions: [
        "Top first: lift each warp loop off its peg IN ORDER and slide it onto the dowel - do not cut the top loops.",
        "Bottom: cut the warps at the bottom pegs, two at a time, and double-knot each released pair snug against the fringe row.",
        "Pull out the scrap-yarn header.",
        "Tie the knotted warp tails in pairs again (staggered) and tuck them up into the back of the fringe knots.",
      ],
      qualityCheck: "Weave hangs level from the dowel; no warp loop skipped or crossed.",
      commonMistake: "Cutting the TOP loops out of habit - then the dowel has nothing to slide through and everything must be needle-hemmed instead.",
      phase: "Finishing",
    },
    {
      stepNumber: 12,
      title: "Weave in the ends",
      estimatedTime: "45 minutes",
      goal: "Every yarn tail invisible; the back tidy enough to not be embarrassing in a mirror",
      toolsNeeded: ["Tapestry needle"],
      materialsNeeded: ["None new"],
      instructions: [
        "Thread each hanging tail onto the needle and run it 2-3 in. vertically through the BACK of its own color section.",
        "Trim flush after threading - never trim a tail that has not been anchored.",
        "Roving tails: split them in half and anchor each half in a different direction (whole roving tails are too fat to hide).",
      ],
      qualityCheck: "Front shows no tails; back shows no dangles longer than 1/2 in.",
      phase: "Finishing",
    },
    {
      stepNumber: 13,
      title: "Steam and block",
      estimatedTime: "20 minutes + overnight hang",
      goal: "A flat, bloomed, relaxed weave that hangs straight",
      toolsNeeded: ["Garment steamer, iron on steam, or a steamy bathroom"],
      materialsNeeded: ["None"],
      instructions: [
        "Hang the piece and steam it generously from 6-8 in. away, front and back - wool blooms visibly, edges relax.",
        "Never touch a hot iron soleplate to the fiber; hover and steam only.",
        "Let it hang overnight so gravity finishes the blocking before the fringe trim.",
      ],
      qualityCheck: "Piece hangs flat against the wall with no curl at the selvedges.",
      phase: "Finishing",
    },
    {
      stepNumber: 14,
      title: "The fringe trim and hanging",
      estimatedTime: "30 minutes",
      goal: "The single most transformative 15 minutes of the project: a deliberate fringe line",
      toolsNeeded: ["Sharpest scissors available", "Yardstick", "Painter's tape"],
      materialsNeeded: ["Cord for the dowel", "Wall hook"],
      instructions: [
        "Decide the line: straight across (modern) or a shallow V dipping 3-4 in. at center (the most common boutique look).",
        "Tape the cut line across the fringe with painter's tape and cut along its edge in long confident strokes.",
        "Cut LESS than you think - hold, step back, look from across the room, then take the second pass. Fringe does not grow back.",
        "Tie the hanging cord to the dowel ends, hang on the rated hook, and go stand across the room feeling smug.",
      ],
      qualityCheck: "The trim line reads intentional from 8 ft; no stray long hairs catch the light.",
      commonMistake: "Freehand trimming without the tape guide - a drifting cut line is the one mistake this project cannot hide.",
      phase: "Finishing",
    },
  ],
  diagrams: [
    {
      id: "dg_loom",
      title: "The lap loom",
      type: "ascii",
      description: "The 28 x 36 in. frame: end rails carry finish-nail pegs at 1/2 in. spacing, corner braces stop racking under warp tension.",
      ascii: `    |||||||||||||||||||||||||||||||||||||||||||||||||   <- 51 nail pegs @ 1/2"
   +==================================================+     (lean pegs outward)
   |\\                    28 in.                      /|
   | \\ brace                                  brace / |
   |                                                  |
   |            36                                    |
   |            in.        (warp runs                 |
   |                        vertically)               |
   | / brace                                  brace \\ |
   |/                                                \\|
   +==================================================+
    |||||||||||||||||||||||||||||||||||||||||||||||||   <- matching peg row`,
      caption: "Build once, weave forever. The braces matter - 100 tensioned warps can fold an unbraced frame.",
    },
    {
      id: "dg_stitches",
      title: "The three techniques",
      type: "ascii",
      description: "Everything in this piece is one of these three moves: tabby (over-under), soumak (wrap over 4, back under 2), rya (folded bundle knotted over a warp pair).",
      ascii: `TABBY            SOUMAK                 RYA KNOT
 _   _   _        __4__      __4__        | |  | |
| |_| |_| |      /     \\__2_/     \\       | |  | |
|_   _   _|      \\__ over 4, under 2      _\\ \\/ /_
  |_| |_|            like a rope  ->     | tails  |
over, under,     2nd pass opposite       | down   |
alternate rows   direction = braid       thru middle`,
      caption: "Tabby is the bread, soumak is the braid line, rya is the fringe. That is the whole vocabulary.",
    },
    {
      id: "dg_layout",
      title: "Band composition map",
      type: "description",
      description:
        "From bottom to top: rya fringe row (14-16 in. tails) -> 3 in. tabby in neutral -> soumak braid -> 2.5 in. roving cloud -> soumak braid -> 2 in. tabby (accent color lives here if chosen) -> roving cloud -> soumak -> tabby to 18 in. total, hemstitched under the dowel. The fringe occupies the bottom third of the hung piece - keep it generous, it is the mass that reads across a room.",
      caption: "Proportions matter more than exact row counts - match the reference photo's ratios.",
    },
  ],
  finishGuide: {
    referenceFinishDescription:
      "No applied finish - the 'finish' is fiber choice and blocking: matte natural wool tones, bloomed loft on the roving sections, a deliberate fringe trim line, and a clean natural-wood dowel.",
    confidence: 88,
    recommendedFinishSystem: [
      "Steam-block the finished weave (Step 13) - the difference between homemade and boutique is mostly this step plus the trim",
      "Overnight gravity hang before the final fringe trim",
      "Taped-guide fringe trim with sharp scissors",
      "Dowel: leave raw, or one wipe of Danish oil for a slight warm-up",
    ],
    budgetOption: ["Skip the steamer - a shower-steamed bathroom and an overnight hang achieve most of the bloom"],
    premiumOption: ["A handheld garment steamer ($25-35) if fiber crafts are becoming A Thing", "Driftwood hanger, sanded lightly, no finish"],
    stainPaintOptions: [
      { name: "None (fiber is the color)", type: "n/a", note: "Choose fiber colors in daylight; craft-store lighting flatters everything." },
      { name: "Danish oil on the dowel", type: "penetrating oil", note: "One wiped coat warms poplar toward oak; optional." },
    ],
    topcoatOptions: [{ name: "None", note: "Never spray anything (including 'fabric protectant') on a wool weave - it mats the loft." }],
    colorMatchingTips: [
      "Match VALUE (light/dark) before hue - neutrals live or die on value contrast between bands.",
      "Photograph your fiber pile in grayscale to check the value spread the way the reference photographs.",
      "One accent band maximum for the boutique look; two reads craft fair.",
    ],
    testBoardInstructions: [
      "Weave 2 in. of each fiber on the loom's edge warps before committing to the layout - your tension sample and color test in one.",
      "Steam the sample and re-judge: wool changes character noticeably after blooming.",
    ],
    commonProblems: [
      { problem: "Edges pulled into an hourglass", fix: "More bubbling per row going forward; existing pull-in relaxes partially with steam. Prevention is Step 6's width checks." },
      { problem: "Roving section looks flat", fix: "Steam generously and tease fibers gently apart with a blunt needle - roving re-lofts well unless it was fork-beaten." },
      { problem: "Weave hangs crooked", fix: "Re-distribute the warp loops along the dowel and check the cord's tie points; crooked is almost always the hang, not the weave." },
    ],
    curingNotes: ["No cure times - fiber is done when it is trimmed.", "First week: expect 1/2 in. of fringe drop as fibers relax; that is why the trim waits for the overnight hang."],
    applicationSteps: ["Steam from 6-8 in., front then back", "Overnight hang", "Taped-line fringe trim", "Hang and admire"],
  },
  miniLessons: [
    {
      id: "ml_tabby_bubbling",
      title: "Tabby and the bubbling habit",
      skillCategory: "Weaving",
      difficulty: "beginner",
      explanation:
        "Tabby is over-under-over-under, alternating each row - the fundamental weave. Bubbling means laying each weft row in as a series of arcs before beating it down, which feeds extra weft length into the row so the edges do not pull inward. Every straight weft row steals width; every bubbled row preserves it.",
      steps: [
        "Open the shed (shed stick on edge, or needle-pick the alternate warps).",
        "Lay the weft across as 4-5 small hills, not a straight line.",
        "Beat down from the center of each hill outward with the fork.",
        "Check the selvedge: it should stand vertical row after row.",
      ],
      commonMistakes: ["Straight-line wefts (the hourglass maker)", "Beating from one edge across, which drags weft toward the beat direction"],
    },
    {
      id: "ml_soumak",
      title: "The soumak braid",
      skillCategory: "Weaving",
      difficulty: "beginner",
      explanation:
        "Soumak wraps the weft around warps (over 4, back under 2) instead of passing between them, so it sits proud of the surface like a laid rope. Two passes in opposite directions lean against each other and read as a braid - the signature horizontal detail in boutique weavings.",
      steps: [
        "Left to right: over 4 warps, back under 2. Repeat across.",
        "Right to left: the same wrap - the opposite lean completes the braid look.",
        "Beat gently; soumak should ride ON the weave, not sink in.",
      ],
      commonMistakes: ["Wrapping over inconsistent warp counts (the rope goes lumpy)", "Pulling wraps tight enough to cinch the width inward"],
    },
    {
      id: "ml_rya_knot",
      title: "Rya knots (the fringe)",
      skillCategory: "Weaving",
      difficulty: "beginner",
      explanation:
        "A rya knot is a folded bundle of fiber lark's-headed around a pair of warps: lay the bundle across two warps, wrap the tails around the outside of each warp and pull them down through the middle. The knot locks under its own weight and density does the visual work.",
      steps: [
        "Pre-cut bundles: 3-4 strands, 32-36 in., folded in half.",
        "Lay across two warps, tails around the outsides, down through the center gap, snug downward.",
        "Two knots per inch for boutique density; push each against the row below.",
      ],
      commonMistakes: ["Skimping on density (sparse fringe is the #1 homemade tell)", "Trimming as you go instead of once at the very end"],
    },
    {
      id: "ml_warp_tension",
      title: "Warp tension: consistent beats tight",
      skillCategory: "Weaving",
      difficulty: "beginner",
      explanation:
        "The warp is the instrument the whole piece is played on. Uneven tension - some strings tight, some slack - makes rows wander and sections bulge, and no weaving skill can compensate. Uniformity matters far more than absolute tightness.",
      steps: [
        "Wind with the cone feeding through a loosely closed fist for natural drag.",
        "Pluck-test every 10 warps: aim for the same soft twang.",
        "Fix drift immediately by taking up slack peg-by-peg toward the un-tied end.",
        "Re-check after the header rows; the header reveals spacing and tension sins early.",
      ],
      commonMistakes: ["Death-grip tension that bows the loom frame", "Ignoring one slack warp ('it is just one') - it telegraphs through every row above it"],
    },
  ],
  mistakePrevention: [
    {
      mistake: "The hourglass (edges pulling inward)",
      whyItHappens: "Straight weft rows have no spare length, so each beat steals a little width; it compounds row over row.",
      howToAvoid: "Bubble every row without exception; check width against a 24 in. mark every 10 rows; doubled selvedge warps resist the pull.",
      howToFix: "Caught within an inch: unweave and redo with bubbling (10 minutes). Caught late: steam recovers a little; otherwise it is a design feature now.",
      affectedSteps: [6, 8, 9],
    },
    {
      mistake: "Sparse, thin fringe",
      whyItHappens: "Rya knots eat fiber 3x faster than people budget, so the last rows get rationed.",
      howToAvoid: "Cut ALL 48 bundles before starting Step 5; the shopping list already includes the 20 percent fiber margin for exactly this.",
      howToFix: "Add a second knot between existing ones - rya rows accept infill invisibly.",
      affectedSteps: [5],
    },
    {
      mistake: "Cutting the top warp loops during removal",
      whyItHappens: "After cutting the bottom loose, momentum keeps the scissors moving.",
      howToAvoid: "Top loops SLIDE onto the dowel uncut - put the scissors down entirely before touching the top edge.",
      howToFix: "Needle-hem the top edge around the dowel with warp thread - an hour of fiddly penance that mostly hides.",
      affectedSteps: [11],
    },
    {
      mistake: "Fork-beating the roving sections",
      whyItHappens: "Habit from the tabby rows.",
      howToAvoid: "Fingers only on roving - press, do not rake.",
      howToFix: "Steam and tease the fibers back apart with a blunt needle; partial recovery only.",
      affectedSteps: [8, 9],
    },
  ],
  commonProblems: [
    {
      problem: "Weave looks uneven / rows wander",
      likelyCauses: ["Uneven warp tension", "Inconsistent beating force", "Weft yarn thickness varying between rows"],
      fix: "Steam-block first - it forgives more than expected. Going forward: pluck-test the warp, beat with the same two-tap rhythm every row.",
      severity: "minor",
    },
    {
      problem: "A warp thread snapped mid-weave",
      likelyCauses: ["Over-tension at winding", "Abrasion at a peg", "A weak spot in the cotton"],
      fix: "Tie a new length to the broken end with a weaver's knot, tension it to match its neighbors by feel, and weave on - the knot hides inside the weft. Do not restart the piece.",
      severity: "moderate",
    },
    {
      problem: "Finished piece curls at the sides",
      likelyCauses: ["Selvedge tension tighter than the field", "Soumak rows cinched at the edges"],
      fix: "Steam heavily along the selvedges and hang with light binder-clip weights on the bottom corners for 48 hours.",
      severity: "minor",
    },
    {
      problem: "Moths (later, in service)",
      likelyCauses: ["Wool + undisturbed darkness + time"],
      fix: "Wool pieces on display are low-risk (light and air deter moths); pieces in storage want a sealed bag and a cedar block. Freezing 72 hours kills an active problem.",
      severity: "minor",
    },
  ],
  safetyReview: {
    overallRisk: "low",
    summary:
      "The lowest-risk project category in the app: hand tools, a hammer, scissors, and fiber. The only findings worth stating are the loom build's basic tool care and honest wall-mounting for the finished piece.",
    hazards: [
      { level: "low", category: "Hand tools", issue: "Hammering ~120 finish nails; sawing four lumber cuts.", mitigation: "Standard care; pilot the screw holes; fingers behind the nail line." },
      { level: "low", category: "Wall mounting", issue: "A ~2 lb hanging over furniture or a bed.", mitigation: "Use the rated picture hook into drywall anchor or stud - not a bare thumbtack; check the cord knots yearly." },
      { level: "low", category: "Fiber dust", issue: "Wool fiber fly during fringe cutting bothers sensitive airways.", mitigation: "Trim in a ventilated room; a mask if you know wool bothers you." },
    ],
    ppe: ["Safety glasses for the nailing session", "That is genuinely the list"],
    childPetNotes: [
      "Hang the finished piece with the fringe out of grab-and-swing reach of toddlers - a determined yank tests your wall hook, not the weave.",
      "Cats regard dangling fringe as a jobs program; hang accordingly or budget for re-knots.",
      "All materials are inert; no cure times, no vapors.",
    ],
    structuralNotes: ["The 10 lb picture hook carries a 2 lb piece with a wide margin. As always: an estimate, not a certified rating - and use a stud or rated anchor, not bare drywall with a nail."],
    finishToxicityNotes: ["No finishes involved. If oiling the dowel, dry the rag flat outdoors."],
    professionalReviewRecommended: false,
  },
  alternatives: [
    {
      id: "alt_one_evening",
      name: "The One-Evening Version",
      focus: "weekend",
      description: "The Minimum Viable Dupe: tabby field + fringe only, all acrylic, straight trim. Loom build included.",
      estimatedCostLow: 30,
      estimatedCostHigh: 55,
      estimatedTime: "1 evening + the loom hour",
      pros: ["Fastest possible wall win", "Proves the scale on your wall", "Loom and warp carry forward"],
      cons: ["Flat texture without the soumak/cloud contrast", "Acrylic sheen up close"],
      keyChanges: ["Single technique", "All acrylic", "Straight fringe"],
    },
    {
      id: "alt_bigger",
      name: "The Statement Wall (36 in. wide)",
      focus: "larger",
      description: "Same design at 36 x 48 for the big empty wall - loom grows to 40 x 48 and fiber roughly doubles.",
      estimatedCostLow: 95,
      estimatedCostHigh: 170,
      estimatedTime: "5-6 evenings",
      pros: ["Over-sofa scale that genuinely replaces art-store spending", "Same three techniques, just more of them"],
      cons: ["The bigger loom is awkward on a lap - it becomes an easel/table project", "Fiber cost roughly doubles"],
      keyChanges: ["Loom 40 x 48", "145 warp ends", "~3 lb roving", "Dowel to 42 in., 1-1/4 in. dia."],
    },
    {
      id: "alt_premium",
      name: "All-Merino Heirloom",
      focus: "premium",
      description: "The Closest Match path: 100% merino everywhere, hand-dyed accent skein, added twill passages, gallery blocking.",
      estimatedCostLow: 95,
      estimatedCostHigh: 160,
      estimatedTime: "4-5 evenings",
      pros: ["Fiber quality visible at touch distance", "Steamed merino bloom is the boutique texture, exactly"],
      cons: ["Hand-dyed skeins are $18-28 each", "Merino roving demands the gentlest handling"],
      keyChanges: ["Merino roving + hand-dyed accent", "Twill passages between bands", "Weighted blocking"],
    },
  ],
  builderHandoff: {
    projectSummary:
      "Commission an inspired-by woven wall hanging: ~24 in. wide x 36 in. long including a dense rya fringe, natural wool palette, tabby/soumak/roving textures, hung on a natural wood dowel or driftwood.",
    referenceStyle: "Boutique modern fiber art (customer will supply photos): banded neutral composition, heavy texture contrast, generous trimmed fringe. Inspired-by commission - same spirit, original piece.",
    desiredDimensions: "24 in. wide, ~36 in. overall including 14-16 in. fringe; sized for the wall spot (customer can confirm with tape measurements).",
    materials: ["Wool or wool-blend preferred over acrylic", "Cotton or linen warp", "Natural wood hanger"],
    finish: "Steam-blocked, deliberate fringe trim (shallow V or straight per reference), tails fully finished on the back.",
    constructionNotes: ["Hemstitched or otherwise locked top edge", "Fringe density at boutique level (~2 rya knots per inch)", "Piece should hang flat without side curl"],
    budgetTarget: "$150-$300 commissioned (customer's DIY alternative is ~$56-101 in materials).",
    qualityExpectations: ["Straight selvedges", "Even warp spacing with no grin-through", "Fringe trim line reads intentional", "Back tidy"],
    questionsForBuilder: [
      "What fiber do you use for the loft sections, and can I approve a sample card?",
      "Straight or V fringe trim for this wall height?",
      "Care recommendations for wool in my climate?",
    ],
    quoteRequestMessage:
      "Hi! I'd love a quote on a commissioned woven wall hanging inspired by a boutique piece (photos attached): about 24 x 36 in. including fringe, natural wool tones, heavy texture contrast with a dense trimmed fringe, on a wood dowel or driftwood. Could you share pricing, timeline, and whether I can approve fiber samples first? Thanks!",
  },
  finalChecklist: [
    "Hangs level (check with a phone level on the dowel)",
    "Selvedges read straight from across the room",
    "Fringe trim line intentional - no stragglers catching light",
    "All tails anchored; back presentable",
    "Wall hook rated and properly anchored (stud or rated anchor)",
    "Steam pass done and overnight hang completed before the trim",
    "Photo for the gallery: reference beside finished piece",
  ],
  maintenance: [
    "Dust seasonally: shake gently outdoors, or cool-air blow-dryer from 12 in.",
    "Vacuuming only through a nylon stocking over the nozzle, and only if you must.",
    "Rotate away from direct sun - wool tones shift after years of full sun.",
    "Moth insurance for wool: display pieces are low-risk; add a cedar block behind the piece if the wall is dark and undisturbed.",
    "Re-check the hanging cord knots and hook once a year.",
    "Fringe re-trim after a year of settling is normal and takes five minutes.",
  ],
  qaNotes: [
    "Budget verified: three required categories sum to $56 low / $93 high; grand total high $101 includes the $8 fringe-fiber buffer; savings computed from the $289 assumed reference price.",
    "Fiber math checked: 97 ends x 48 in. warp = ~130 yd of the 800 yd cone; 48 rya bundles x 3.5 strands x 34 in. plus field wefts lands inside 1.5 lb of roving with ~20 percent margin.",
    "All three techniques used in the steps have matching mini-lessons; no step references a tool absent from the tools list.",
    "Safety review at overall low; wall-mount guidance uses conservative language, no load ratings claimed.",
    "Brand-safe: reference described generically; inspired-by framing throughout.",
  ],
  confidenceScore: 86,
  createdAt: T,
  updatedAt: T,
};
